// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/VectorMapCard.svelte
<script>
  import Card from "../../components/Cards/Card.svelte";
  import FusionCharts from "fusioncharts";
  import Charts from "fusioncharts/fusioncharts.charts";
  import Maps from "fusioncharts/fusioncharts.maps";
  import World from "fusioncharts/maps/fusioncharts.world";
  import FusionTheme from "fusioncharts/themes/fusioncharts.theme.fusion";
  import SvelteFC, { fcRoot } from "svelte-fusioncharts";

  fcRoot(FusionCharts, Maps, World, FusionTheme);
  let dataSource = {
      chart: {
        labelsepchar: ": ",
        entityFillHoverColor: "#D2D7DD",
        theme: "fusion",
        showlegend: "0",
        showLabels: "0"
      },
      colorrange: {
        minvalue: "0",
        code: "#FFE0B2",
        gradient: "1",
        color: [
          {
            minvalue: "0",
            maxvalue: "0.5",
            color: "#ADB5BD"
          },
          {
            minvalue: "0.5",
            maxvalue: "1.0",
            color: "#ADB5BD"
          },
          {
            minvalue: "1.0",
            maxvalue: "2.0",
            color: "#F1F4F8"
          },
          {
            minvalue: "2.0",
            maxvalue: "3.0",
            color: "#D7DCE2"
          }
        ]
      },
      data: [
        {
          id: "NA",
          value: ".82",
          showLabel: "1"
        },
        {
          id: "SA",
          value: "2.04",
          showLabel: "1"
        },
        {
          id: "AS",
          value: "1.78",
          showLabel: "1"
        },
        {
          id: "EU",
          value: ".40",
          showLabel: "1"
        },
        {
          id: "AF",
          value: "2.58",
          showLabel: "1"
        },
        {
          id: "AU",
          value: "1.30",
          showLabel: "1"
        }
      ]
    },
    chartConfig = {
      type: "world",
      renderAt: "chart-container",
      width: "100%",
      height: 350,
      dataSource
    };
</script>

<Card nobody={true} className="widget-calendar">
  <div class="card-header">
    <div class="row align-items-center">
      <div class="col-8">
        <!-- Title -->
        <h5 class="h3 mb-0">Real time</h5>
      </div>
      <div class="col-4 text-right">
        <a href="#!" class="btn btn-sm btn-neutral">Action</a>
      </div>
    </div>
  </div>
  <div class="card-body">
    <SvelteFC {...chartConfig} />
  </div>
  <div class="list-group list-group-flush list my--3">
    <div class="list-group-item px-0">
      <div class="row align-items-center">
        <div class="col-md-auto">
          <!-- Country flag -->
          <img src="../../../../img/icons/flags/US.png" alt="Country flag" />
        </div>
        <div class="col">
          <small>Country:</small>
          <h5 class="mb-0">United States</h5>
        </div>
        <div class="col">
          <small>Visits:</small>
          <h5 class="mb-0">2500</h5>
        </div>
        <div class="col">
          <small>Bounce:</small>
          <h5 class="mb-0">30%</h5>
        </div>
      </div>
    </div>
        <div class="list-group-item px-0">
      <div class="row align-items-center">
        <div class="col-md-auto">
          <!-- Country flag -->
          <img src="../../../../img/icons/flags/DE.png" alt="Country flag">
        </div>
        <div class="col">
          <small>Country:</small>
          <h5 class="mb-0">Germany</h5>
        </div>
        <div class="col">
          <small>Visits:</small>
          <h5 class="mb-0">2500</h5>
        </div>
        <div class="col">
          <small>Bounce:</small>
          <h5 class="mb-0">30%</h5>
        </div>
      </div>
    </div>
        <div class="list-group-item px-0">
      <div class="row align-items-center">
        <div class="col-md-auto">
          <!-- Country flag -->
          <img src="../../../../img/icons/flags/GB.png" alt="Country flag">
        </div>
        <div class="col">
          <small>Country:</small>
          <h5 class="mb-0">Great Britain</h5>
        </div>
        <div class="col">
          <small>Visits:</small>
          <h5 class="mb-0">2500</h5>
        </div>
        <div class="col">
          <small>Bounce:</small>
          <h5 class="mb-0">30%</h5>
        </div>
      </div>
    </div>
  </div>
</Card>

// extracted_templates/vue-laravel/vue-argon-dashboard-pro-laravel-bs4-master/vue-argon-dashboard-pro-laravel-bs4-master/vue-argon-dashboard-pro/src/views/Widgets/VectorMapCard.vue
<template>
    <div class="card widget-calendar">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col-8">
                    <!-- Title -->
                    <h5 class="h3 mb-0">Real time</h5>
                </div>
                <div class="col-4 text-right">
                    <a href="#!" class="btn btn-sm btn-neutral">Action</a>
                </div>
            </div>
        </div>

      <div class="card-body">
        <world-map class="vector-map vector-map-sm"
                         :map-data="mapData"
                         :points="points">
        </world-map>

        <ul class="list-group list-group-flush list my--3">
          <li class="list-group-item px-0">
            <div class="row align-items-center">
              <div class="col-auto">
                <!-- Country flag -->
                <img src="/img/icons/flags/US.png" alt="Country flag">
              </div>
              <div class="col">
                <small>Country:</small>
                <h5 class="mb-0">United States</h5>
              </div>
              <div class="col">
                <small>Visits:</small>
                <h5 class="mb-0">2500</h5>
              </div>
              <div class="col">
                <small>Bounce:</small>
                <h5 class="mb-0">30%</h5>
              </div>
            </div>
          </li>
          <li class="list-group-item px-0">
            <div class="row align-items-center">
              <div class="col-auto">
                <!-- Country flag -->
                <img src="/img/icons/flags/DE.png" alt="Country flag">
              </div>
              <div class="col">
                <small>Country:</small>
                <h5 class="mb-0">Germany</h5>
              </div>
              <div class="col">
                <small>Visits:</small>
                <h5 class="mb-0">2500</h5>
              </div>
              <div class="col">
                <small>Bounce:</small>
                <h5 class="mb-0">30%</h5>
              </div>
            </div>
          </li>
          <li class="list-group-item px-0">
            <div class="row align-items-center">
              <div class="col-auto">
                <!-- Country flag -->
                <img src="/img/icons/flags/GB.png" alt="Country flag">
              </div>
              <div class="col">
                <small>Country:</small>
                <h5 class="mb-0">Great Britain</h5>
              </div>
              <div class="col">
                <small>Visits:</small>
                <h5 class="mb-0">2500</h5>
              </div>
              <div class="col">
                <small>Bounce:</small>
                <h5 class="mb-0">30%</h5>
              </div>
            </div>
          </li>
        </ul>

      </div>

    </div>
</template>
<script>
  import WorldMap from '@/components/WorldMap/WorldMap.vue';
  export default {
    name: 'map-card',
    components: {
      WorldMap
    },
    data() {
      return {
        mapData: {
          AUS: 760,
          BRA: 900,
          CAN: 120,
          DEU: 1300,
          FRA: 540,
          GBR: 690,
          GEO: 200,
          IND: 200,
          ROU: 600,
          RUS: 757,
          USA: 1800
        },
        points: [
          {
            name: 'Brazil',
            centered: 'BRA',
          },
          {
            name: 'France',
            centered: 'FRA',
          },
          {
            name: 'Italy',
            centered: 'ITA',
          },
          {
            name: 'Oman',
            centered: 'OMN',
          },
          {
            name: 'Indonesia',
            centered: 'IDN',
          },
          {
            name: 'Romania',
            centered: 'ROU',
          }
        ]
      }
    }
  }
</script>
