// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/public/pricing.svelte
<script>
  import Card from "../../components/Cards/Card.svelte";
  import BaseButton from "../../components/BaseButton.svelte";
  document.body.classList = "bg-default";
  import { fade, scale } from "svelte/transition";
</script>

<div in:scale={{ y: 200, duration: 500 }} out:scale={{ y: 200, duration: 100 }}>
  <div class="header bg-gradient-danger py-7 py-lg-8 pt-lg-9">
    <div class="container">
      <div class="header-body text-center mb-7">
        <div class="row justify-content-center">
          <div class="px-5 col-md-8 col-lg-6 col-xl-5">
            <h1 class="text-white">Choose the best plan for your business</h1>
          </div>
        </div>
      </div>
    </div>
    <div class="separator separator-bottom separator-skew zindex-100">
      <svg
        x="0"
        y="0"
        viewBox="0 0 2560 100"
        preserveAspectRatio="none"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg">
        <polygon points="2560 0 2560 100 0 100" class="fill-default" />
      </svg>
    </div>
  </div>
  <div class="mt--8 pb-5 container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="pricing flex-column flex-md-row mb-3 card-group">
          <Card
            className="card card-pricing border-0 text-center mb-4"
            headerClasses="bg-transparent"
            bodyClasses="px-lg-7"
            footerClasses="bg-transparent">

            <h4
              slot="header"
              class="header text-uppercase ls-1 text-primary py-3 mb-0">
              Bravo pack
            </h4>
            <div class="display-2">$49</div>
            <span class="text-muted">per application</span>
            <ul class="list-unstyled my-4">
              <li>
                <div class="d-flex align-items-center">
                  <div>
                    <div
                      class="icon icon-xs icon-shape bg-gradient-primary shadow
                      rounded-circle text-white">
                      <i class="fas fa-terminal" />
                    </div>
                  </div>
                  <div>
                    <span class="pl-2">Complete documentation</span>
                  </div>
                </div>
              </li>
              <li>
                <div class="d-flex align-items-center">
                  <div>
                    <div
                      class="icon icon-xs icon-shape bg-gradient-primary shadow
                      rounded-circle text-white">
                      <i class="fas fa-pen-fancy" />
                    </div>
                  </div>
                  <div>
                    <span class="pl-2">Working materials in Sketch</span>
                  </div>
                </div>
              </li>
              <li>
                <div class="d-flex align-items-center">
                  <div>
                    <div
                      class="icon icon-xs icon-shape bg-gradient-primary shadow
                      rounded-circle text-white">
                      <i class="fas fa-hdd" />
                    </div>
                  </div>
                  <div>
                    <span class="pl-2">2GB cloud storage</span>
                  </div>
                </div>
              </li>
            </ul>
            <BaseButton type="primary" className="mb-3">
              Start free trial
            </BaseButton>
            <a slot="footer" href="#!" class="text-light">Request a demo</a>
          </Card>
          <Card
            className="card card-pricing zoom-in shadow-lg rounded border-0
            text-center mb-4 bg-gradient-info"
            gradient="info"
            headerClasses="bg-transparent"
            bodyClasses="px-lg-7"
            footerClasses="bg-transparent">

            <h4 slot="header" class="text-uppercase ls-1 text-white py-3 mb-0">
              Alpha pack
            </h4>
            <div class="display-1 text-white">$199</div>
            <span class="text-white">per application</span>
            <ul class="list-unstyled my-4">
              <li>
                <div class="d-flex align-items-center">
                  <div>
                    <div
                      class="icon icon-xs icon-shape bg-white shadow
                      rounded-circle text-muted">
                      <i class="fas fa-terminal" />
                    </div>
                  </div>
                  <div>
                    <span class="pl-2 text-white">Complete documentation</span>
                  </div>
                </div>
              </li>
              <li>
                <div class="d-flex align-items-center">
                  <div>
                    <div
                      class="icon icon-xs icon-shape bg-white shadow
                      rounded-circle text-muted">
                      <i class="fas fa-pen-fancy" />
                    </div>
                  </div>
                  <div>
                    <span class="pl-2 text-white">
                      Working materials in Sketch
                    </span>
                  </div>
                </div>
              </li>
              <li>
                <div class="d-flex align-items-center">
                  <div>
                    <div
                      class="icon icon-xs icon-shape bg-white shadow
                      rounded-circle text-muted">
                      <i class="fas fa-hdd" />
                    </div>
                  </div>
                  <div>
                    <span class="pl-2 text-white">2GB cloud storage</span>
                  </div>
                </div>
              </li>
            </ul>
            <BaseButton type="secondary" size="lg" className="mb-3">
              Start free trial
            </BaseButton>

            <a slot="footer" href="#!" class="text-white">Contact sales</a>
          </Card>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-lg-center px-3 mt-5">
      <div>
        <div
          class="icon icon-shape bg-gradient-white shadow rounded-circle
          text-primary">
          <i class="ni ni-building text-primary" />
        </div>
      </div>
      <div class="col-lg-6">
        <p class="text-white">
          <strong>The Arctic Ocean</strong>
          freezes every winter and much of the sea-ice then thaws every summer,
          and that process will continue whatever..
        </p>
      </div>
    </div>
    <div class="row row-grid justify-content-center">
      <div class="col-lg-10">
        <div class="table-responsive">
          <table class="table tablesorter table table-dark mt-5">
            <thead class="">
              <tr>
                <th scope="col" class="px-0 bg-transparent">
                  <span class="text-light font-weight-700">Features</span>
                </th>
                <th scope="col" class="text-center bg-transparent">
                  Bravo Pack
                </th>
                <th scope="col" class="text-center bg-transparent">
                  Alpha Pack
                </th>
              </tr>
            </thead>
            <tbody class="">
              <tr>
                <td class="px-0">IMAP/POP Support</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
              </tr>
              <tr>
                <td class="px-0">Email Forwarding</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
              </tr>
              <tr>
                <td class="px-0">Active Sync</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
              </tr>
              <tr>
                <td class="px-0">Multiple domain hosting</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">
                  <span class="text-sm text-light">
                    Limited to 1 domain only
                  </span>
                </td>
              </tr>
              <tr>
                <td class="px-0">Additional storage upgrade</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
              </tr>
              <tr>
                <td class="px-0">30MB Attachment Limit</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">-</td>
              </tr>
              <tr>
                <td class="px-0">Password protected / Expiry links</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">-</td>
              </tr>
              <tr>
                <td class="px-0">Unlimited Custom Apps</td>
                <td class="text-center">
                  <i class="fas fa-check text-success" />
                </td>
                <td class="text-center">-</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

// extracted_templates/react/argon-dashboard-pro-material-ui-v1.0.0/src/views/auth/Pricing.js
import React from "react";
import clsx from "clsx";
// @material-ui/core components
import { makeStyles } from "@material-ui/core/styles";
import { useTheme } from "@material-ui/core/styles";
import Avatar from "@material-ui/core/Avatar";
import Box from "@material-ui/core/Box";
import Container from "@material-ui/core/Container";
import Grid from "@material-ui/core/Grid";
import Table from "@material-ui/core/Table";
import TableBody from "@material-ui/core/TableBody";
import TableCell from "@material-ui/core/TableCell";
import TableContainer from "@material-ui/core/TableContainer";
import TableHead from "@material-ui/core/TableHead";
import TableRow from "@material-ui/core/TableRow";
// @material-ui/icons components
import Business from "@material-ui/icons/Business";
import Check from "@material-ui/icons/Check";

// core components
import AuthHeader from "components/Headers/AuthHeader.js";
import CardPricing from "components/Cards/Pricing/CardPricing.js";
import CardPricingGradient from "components/Cards/Pricing/CardPricingGradient.js";
import componentStyles from "assets/theme/views/auth/pricing.js";
import cardGroupStyles from "assets/theme/components/cards/card-group.js";
import buttonsStyles from "assets/theme/components/button.js";

const useStyles = makeStyles(componentStyles);
const useStylesCardGroup = makeStyles(cardGroupStyles);
const useStylesButtons = makeStyles(buttonsStyles);

function Pricing() {
  const classes = {
    ...useStyles(),
    ...useStylesCardGroup(),
    ...useStylesButtons(),
  };
  const theme = useTheme();
  const tableRows = [
    {
      FIELD1: "IMAP/POP Support",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
    },
    {
      FIELD1: "Email Forwarding",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
    },
    {
      FIELD1: "Active Sync",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
    },
    {
      FIELD1: "Multiple domain hosting",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: "Limited to 1 domain only",
    },
    {
      FIELD1: "Additional storage upgrade",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
    },
    {
      FIELD1: "30MB Attachment Limit",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: "-",
    },
    {
      FIELD1: "Password protected / Expiry links",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: "-",
    },
    {
      FIELD1: "Unlimited Custom Apps",
      FIELD2: (
        <Box
          width="1.25rem!important"
          height="1.25rem!important"
          color={theme.palette.success.main}
          component={Check}
        />
      ),
      FIELD3: "-",
    },
  ];
  return (
    <>
      <AuthHeader title="Choose the best plan for your business" />
      {/* Page content */}
      <Container
        component={Box}
        maxWidth="xl"
        marginTop="-8rem"
        paddingBottom="3rem"
        position="relative"
        zIndex="101"
      >
        <Box component={Grid} container justifyContent="center">
          <Grid item xs={12} lg={10}>
            <Box
              marginBottom="3rem"
              className={clsx(classes.cardGroup, classes.flexMdRow)}
            >
              <CardPricing />
              <CardPricingGradient />
            </Box>
          </Grid>
        </Box>
        <Box
          display="flex"
          paddingLeft="1rem"
          paddingRight="1rem"
          marginTop="3rem"
          className={classes.justifyContentLgCenter}
          color={theme.palette.white.main}
          alignItems="center"
        >
          <div>
            <Avatar className={classes.avatarRoot}>
              <Box
                component={Business}
                color={theme.palette.primary.main}
                width="1.5rem!important"
                height="1.5rem!important"
              />
            </Avatar>
          </div>
          <Grid item xs={12} lg={6}>
            <Box
              component="p"
              fontWeight="300"
              lineHeight="1.7"
              marginBottom="1rem"
              marginTop="1rem"
            >
              <strong>The Arctic Ocean</strong> freezes every winter and much of
              the sea-ice then thaws every summer, and that process will
              continue whatever.
            </Box>
          </Grid>
        </Box>
        <Grid container component={Box} justifyContent="center">
          <Grid item xs={12} lg={10}>
            <TableContainer component={Box} marginTop="3rem">
              <Table className={classes.table} aria-label="simple table">
                <TableHead>
                  <TableRow>
                    <TableCell algin="left" className={classes.tableCellHead}>
                      Features
                    </TableCell>
                    <TableCell align="center" className={classes.tableCellHead}>
                      Bravo Pack
                    </TableCell>
                    <TableCell align="center" className={classes.tableCellHead}>
                      Alpha Pack
                    </TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {tableRows.map((prop, key) => (
                    <TableRow key={key} className={classes.tableRowBody}>
                      <TableCell algin="left" className={classes.tableCellBody}>
                        {prop.FIELD1}
                      </TableCell>
                      <TableCell
                        align="center"
                        className={classes.tableCellBody}
                      >
                        {prop.FIELD2}
                      </TableCell>
                      <TableCell
                        align="center"
                        className={classes.tableCellBody}
                      >
                        {prop.FIELD3}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          </Grid>
        </Grid>
      </Container>
    </>
  );
}

export default Pricing;
