// extracted_templates/react-node/argon-dashboard-pro-react-nodejs-v1.0.0/argon-dashboard-pro-react-nodejs-v1.0.0/frontend/src/views/pages/Calendar.js
/*!

=========================================================
* Argon Dashboard PRO React Nodejs - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard-pro-react-nodejs
* Copyright 2021 Creative Tim (http://www.creative-tim.com)

* Coded by Creative Tim
* Coded by ProjectData

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*/
import React from "react";
// nodejs library that concatenates classes
import classnames from "classnames";
// JavaScript library that creates a callendar with events
import { Calendar } from "@fullcalendar/core";
import dayGridPlugin from "@fullcalendar/daygrid";
import interaction from "@fullcalendar/interaction";
// react component used to create sweet alerts
import ReactBSAlert from "react-bootstrap-sweetalert";
// reactstrap components
import {
  Button,
  ButtonGroup,
  Card,
  CardHeader,
  CardBody,
  FormGroup,
  Form,
  Input,
  Modal,
  Container,
  Row,
  Col,
  Breadcrumb,
  BreadcrumbItem,
} from "reactstrap";
// core components

import { events as eventsVariables } from "variables/general.js";
import { getTasksByUser } from "network/ApiAxios";
import { createTask } from "network/ApiAxios";
import { editTask } from "network/ApiAxios";
import { deleteTask } from "network/ApiAxios";

let calendar;

function CalendarView() {
  const [events, setEvents] = React.useState([]);
  const [alert, setAlert] = React.useState(null);
  const [modalAdd, setModalAdd] = React.useState(false);
  const [modalChange, setModalChange] = React.useState(false);
  const [startDate, setStartDate] = React.useState(null);
  const [endDate, setEndDate] = React.useState(null);
  const [radios, setRadios] = React.useState(null);
  const [eventId, setEventId] = React.useState(null);
  const [eventTitle, setEventTitle] = React.useState(null);
  const [eventDescription, setEventDescription] = React.useState(null);
  // eslint-disable-next-line
  const [event, setEvent] = React.useState(null);
  const [currentDate, setCurrentDate] = React.useState(null);

  const [refresh, setRefresh] = React.useState(false);

  const calendarRef = React.useRef(null);
  React.useEffect(() => {
    const user = JSON.parse(localStorage.getItem("user"));
    if (!user) {
      console.log("nu eee");
      return;
    } 
    const {_id: userId} = user;
    const runAsync = async () => {
      const {data} = await getTasksByUser(userId);
      const {tasks} = data;
      console.log(tasks);
      setEvents(tasks.map(task => ({
        id: task._id,
        start: new Date(task.startDate),
        end: new Date(new Date(task.endDate) - ( 3600 * 1000 * 24)),
        title: task.title,
        description: task.description,
        className: task.color,
        allDay: true
      })))
    }
    runAsync();
    // eslint-disable-next-line
  }, [refresh]);

  React.useEffect(() => {
    createCalendar();
  }, [events]);

  const createCalendar = () => {
    console.log(events);
    calendar = new Calendar(calendarRef.current, {
      plugins: [interaction, dayGridPlugin],
      initialView: "dayGridMonth",
      selectable: true,
      editable: true,
      events: events,
      headerToolbar: "",
      // Add new event
      select: (info) => {
        setModalAdd(true);
        setStartDate(info.startStr);
        setEndDate(info.endStr);
        setRadios("bg-info");
      },
      // Edit calendar event action
      eventClick: ({event}) => {
        console.log(event.id, event.extendedProps);
        setEventId(event.id);
        setEventTitle(event.title);
        setEventDescription(event.extendedProps.description);
        setRadios("bg-info");
        setEvent(event);
        setModalChange(true);
      },
    });
    calendar.render();
    setCurrentDate(calendar.view.title);
  };
  const changeView = (newView) => {
    calendar.changeView(newView);
    setCurrentDate(calendar.view.title);
  };
  const addNewEvent = async () => {
    var newEvents = events;
    const {_id: id} = JSON.parse(localStorage.getItem("user"));
    const {data} = await createTask(id, eventTitle, eventDescription, radios, startDate, endDate);
    if (data.success) {
      const {task} = data;
      console.log(data);
      newEvents.push({
        title: eventTitle,
        start: startDate,
        end: endDate,
        className: radios,
        id: task._id,
        description: eventDescription,
        allDay: true
      });
      calendar.addEvent({
        title: eventTitle,
        start: startDate,
        end: endDate,
        className: radios,
        id: task._id,
        description: eventDescription,
        allDay: true
      });
    }
    console.log(newEvents);
    setModalAdd(false);
    setEvents(newEvents);
    setStartDate(undefined);
    setEndDate(undefined);
    setRadios("bg-info");
    setEventTitle(undefined);
  };
  const changeEvent = async () => {

    const newEvents = [...events];
    const {data} = await editTask(eventId, eventTitle, eventDescription, radios, startDate, endDate);

    setRefresh(!refresh);

    setModalChange(false);
    setEvents(newEvents);
    setRadios("bg-info");
    setEventTitle(undefined);
    setEventDescription(undefined);
    setEventId(undefined);
    setEvent(undefined);
  };
  const deleteEventSweetAlert = () => {
    setAlert(
      <ReactBSAlert
        warning
        style={{ display: "block", marginTop: "-100px" }}
        title="Are you sure?"
        onConfirm={() => {
          setAlert(false);
          setRadios("bg-info");
          setEventTitle(undefined);
          setEventDescription(undefined);
          setEventId(undefined);
        }}
        onCancel={() => deleteEvent()}
        confirmBtnCssClass="btn-secondary"
        cancelBtnBsStyle="danger"
        confirmBtnText="Cancel"
        cancelBtnText="Yes, delete it"
        showCancel
        btnSize=""
      >
        You won't be able to revert this!
      </ReactBSAlert>
    );
  };
  const deleteEvent = async () => {
    const {data} = await deleteTask(eventId);
    setRefresh(!refresh);
    var newEvents = events.filter((prop) => prop.id + "" !== eventId);
    setEvent(undefined);
    setAlert(
      <ReactBSAlert
        success
        style={{ display: "block", marginTop: "-100px" }}
        title="Success"
        onConfirm={() => setAlert(null)}
        onCancel={() => setAlert(null)}
        confirmBtnBsStyle="primary"
        confirmBtnText="Ok"
        btnSize=""
      >
        A few words about this sweet alert ...
      </ReactBSAlert>
    );
    setModalChange(false);
    setEvents(newEvents);
    setRadios("bg-info");
    setEventTitle(undefined);
    setEventDescription(undefined);
    setEventId(undefined);
    setEvent(undefined);
  };

  return (
    <>
      {alert}
      <div className="header header-dark bg-info pb-6 content__title content__title--calendar">
        <Container fluid>
          <div className="header-body">
            <Row className="align-items-center py-4">
              <Col lg="6">
                <h6 className="fullcalendar-title h2 text-white d-inline-block mb-0 mr-1">
                  {currentDate}
                </h6>
                <Breadcrumb
                  className="d-none d-md-inline-block ml-lg-4"
                  listClassName="breadcrumb-links breadcrumb-dark"
                >
                  <BreadcrumbItem>
                    <a href="#pablo" onClick={(e) => e.preventDefault()}>
                      <i className="fas fa-home" />
                    </a>
                  </BreadcrumbItem>
                  <BreadcrumbItem>
                    <a href="#pablo" onClick={(e) => e.preventDefault()}>
                      Dashboard
                    </a>
                  </BreadcrumbItem>
                  <BreadcrumbItem aria-current="page" className="active">
                    Calendar
                  </BreadcrumbItem>
                </Breadcrumb>
              </Col>
              <Col className="mt-3 mt-md-0 text-md-right" lg="6">
                <Button
                  className="fullcalendar-btn-prev btn-neutral"
                  color="default"
                  onClick={() => {
                    calendar.prev();
                    setCurrentDate(calendar.view.title);
                  }}
                  size="sm"
                >
                  <i className="fas fa-angle-left" />
                </Button>
                <Button
                  className="fullcalendar-btn-next btn-neutral"
                  color="default"
                  onClick={() => {
                    calendar.next();
                    setCurrentDate(calendar.view.title);
                  }}
                  size="sm"
                >
                  <i className="fas fa-angle-right" />
                </Button>
                <Button
                  className="btn-neutral"
                  color="default"
                  data-calendar-view="month"
                  onClick={() => changeView("dayGridMonth")}
                  size="sm"
                >
                  Month
                </Button>
                <Button
                  className="btn-neutral"
                  color="default"
                  data-calendar-view="basicWeek"
                  onClick={() => changeView("dayGridWeek")}
                  size="sm"
                >
                  Week
                </Button>
                <Button
                  className="btn-neutral"
                  color="default"
                  data-calendar-view="basicDay"
                  onClick={() => changeView("dayGridDay")}
                  size="sm"
                >
                  Day
                </Button>
              </Col>
            </Row>
          </div>
        </Container>
      </div>
      <Container className="mt--6" fluid>
        <Row>
          <div className="col">
            <Card className="card-calendar">
              <CardHeader>
                <h5 className="h3 mb-0">Calendar</h5>
              </CardHeader>
              <CardBody className="p-0">
                <div
                  className="calendar"
                  data-toggle="calendar"
                  id="calendar"
                  ref={calendarRef}
                />
              </CardBody>
            </Card>
            <Modal
              isOpen={modalAdd}
              toggle={() => setModalAdd(false)}
              className="modal-dialog-centered modal-secondary"
            >
              <div className="modal-body">
                <form className="new-event--form">
                  <FormGroup>
                    <label className="form-control-label">Event title</label>
                    <Input
                      className="form-control-alternative new-event--title"
                      placeholder="Event Title"
                      type="text"
                      onChange={(e) => setEventTitle(e.target.value)}
                    />
                  </FormGroup>
                  <FormGroup className="mb-0">
                    <label className="form-control-label d-block mb-3">
                      Status color
                    </label>
                    <ButtonGroup
                      className="btn-group-toggle btn-group-colors event-tag"
                      data-toggle="buttons"
                    >
                      <Button
                        className={classnames("bg-info", {
                          active: radios === "bg-info",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-info")}
                      />
                      <Button
                        className={classnames("bg-warning", {
                          active: radios === "bg-warning",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-warning")}
                      />
                      <Button
                        className={classnames("bg-danger", {
                          active: radios === "bg-danger",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-danger")}
                      />
                      <Button
                        className={classnames("bg-success", {
                          active: radios === "bg-success",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-success")}
                      />
                      <Button
                        className={classnames("bg-default", {
                          active: radios === "bg-default",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-default")}
                      />
                      <Button
                        className={classnames("bg-primary", {
                          active: radios === "bg-primary",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-primary")}
                      />
                    </ButtonGroup>
                  </FormGroup>
                  <FormGroup>
                    <label className="form-control-label">Description</label>
                    <Input
                      className="form-control-alternative edit-event--description textarea-autosize"
                      placeholder="Event Desctiption"
                      type="textarea"
                      defaultValue={eventDescription}
                      onChange={(e) => setEventDescription(e.target.value)}
                    />
                    <i className="form-group--bar" />
                  </FormGroup>
                </form>
              </div>
              <div className="modal-footer">
                <Button
                  className="new-event--add"
                  color="primary"
                  type="button"
                  onClick={addNewEvent}
                >
                  Add event
                </Button>
                <Button
                  className="ml-auto"
                  color="link"
                  type="button"
                  onClick={() => setModalAdd(false)}
                >
                  Close
                </Button>
              </div>
            </Modal>
            <Modal
              isOpen={modalChange}
              toggle={() => setModalChange(false)}
              className="modal-dialog-centered modal-secondary"
            >
              <div className="modal-body">
                <Form className="edit-event--form">
                  <FormGroup>
                    <label className="form-control-label">Event title</label>
                    <Input
                      className="form-control-alternative edit-event--title"
                      placeholder="Event Title"
                      type="text"
                      defaultValue={eventTitle}
                      onChange={(e) => setEventTitle(e.target.value)}
                    />
                  </FormGroup>
                  <FormGroup>
                    <label className="form-control-label d-block mb-3">
                      Status color
                    </label>
                    <ButtonGroup
                      className="btn-group-toggle btn-group-colors event-tag mb-0"
                      data-toggle="buttons"
                    >
                      <Button
                        className={classnames("bg-info", {
                          active: radios === "bg-info",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-info")}
                      />
                      <Button
                        className={classnames("bg-warning", {
                          active: radios === "bg-warning",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-warning")}
                      />
                      <Button
                        className={classnames("bg-danger", {
                          active: radios === "bg-danger",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-danger")}
                      />
                      <Button
                        className={classnames("bg-success", {
                          active: radios === "bg-success",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-success")}
                      />
                      <Button
                        className={classnames("bg-default", {
                          active: radios === "bg-default",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-default")}
                      />
                      <Button
                        className={classnames("bg-primary", {
                          active: radios === "bg-primary",
                        })}
                        color=""
                        type="button"
                        onClick={() => setRadios("bg-primary")}
                      />
                    </ButtonGroup>
                  </FormGroup>
                  <FormGroup>
                    <label className="form-control-label">Description</label>
                    <Input
                      className="form-control-alternative edit-event--description textarea-autosize"
                      placeholder="Event Desctiption"
                      type="textarea"
                      defaultValue={eventDescription}
                      onChange={(e) => setEventDescription(e.target.value)}
                    />
                    <i className="form-group--bar" />
                  </FormGroup>
                  <input className="edit-event--id" type="hidden" />
                </Form>
              </div>
              <div className="modal-footer">
                <Button color="primary" onClick={changeEvent}>
                  Update
                </Button>
                <Button
                  color="danger"
                  onClick={() => {
                    setModalChange(false);
                    deleteEventSweetAlert();
                  }}
                >
                  Delete
                </Button>
                <Button
                  className="ml-auto"
                  color="link"
                  onClick={() => setModalChange(false)}
                >
                  Close
                </Button>
              </div>
            </Modal>
          </div>
        </Row>
      </Container>
    </>
  );
}

export default CalendarView;

// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/calendar.svelte
<script>
  import FullCalendar from "svelte-fullcalendar";
  import dayGridPlugin from "@fullcalendar/daygrid";
  import timeGridPlugin from "@fullcalendar/timegrid";
  import interactionPlugin from "@fullcalendar/interaction";
  import BaseHeader from "../../components/BaseHeader.svelte";
  import BaseButton from "../../components/BaseButton.svelte";
  import RouteBreadcrumb from "../../components/Breadcrumb/RouteBreadcrumb.svelte";
  import Card from "../../components/Cards/Card.svelte";
  import Modal from "../../components/Modal.svelte";
  import BaseInput from "../../components/Inputs/BaseInput.svelte";
  import "~@fullcalendar/core/main.css";
  import "~@fullcalendar/core/main.css";
  import "~@fullcalendar/daygrid/main.css";
  import "~@fullcalendar/timegrid/main.css";
  import "~@fullcalendar/interaction/main.css";
  import { onMount } from "svelte";
  onMount(function() {
    let topmenu = document.getElementsByTagName("nav").item(0);
    topmenu.classList.add("bg-danger");
    topmenu.classList.add("navbar-dark");
    topmenu.classList.remove("navbar-light");
    let search = document.getElementsByTagName("form").item(0);
    search.classList.remove("navbar-search-dark");
    search.classList.add("navbar-search-light");
  });

  // rollup must be configured to do this
  export let name = "Calendar";
  export let parent = "";
  let calendarPlugins = [dayGridPlugin, timeGridPlugin, interactionPlugin];
  let defaultView = "dayGridMonth";
  const today = new Date();
  const y = today.getFullYear();
  const m = today.getMonth();
  const d = today.getDate();
  let yearAndMonth;
  if (m + 1 < 10) {
    yearAndMonth = `${y}-0${m + 1}`;
  } else {
    yearAndMonth = `${y}-${m + 1}`;
  }
  let events = [
    {
      title: "Call with Dave",
      start: `${yearAndMonth}-18`,
      end: `${yearAndMonth}-18`,
      className: "bg-red",
      allDay: true
    },

    {
      title: "Lunch meeting",
      start: `${yearAndMonth}-21`,
      end: `${yearAndMonth}-22`,
      className: "bg-orange",
      allDay: true
    },

    {
      title: "All day conference",
      start: `${yearAndMonth}-29`,
      end: `${yearAndMonth}-29`,
      className: "bg-green",
      allDay: true
    },

    {
      title: "Meeting with Mary",
      start: `${yearAndMonth}-01`,
      end: `${yearAndMonth}-01`,
      className: "bg-blue",
      allDay: true
    },

    {
      title: "Winter Hackaton",
      start: `${yearAndMonth}-03`,
      end: `${yearAndMonth}-03`,
      className: "bg-red",
      allDay: true
    },

    {
      title: "Digital event",
      start: `${yearAndMonth}-07`,
      end: `${yearAndMonth}-09`,
      className: "bg-orange",
      allDay: true
    },

    {
      title: "Marketing event",
      start: `${yearAndMonth}-10`,
      end: `${yearAndMonth}-10`,
      className: "bg-purple",
      allDay: true
    },

    {
      title: "Dinner with Family",
      start: `${yearAndMonth}-19`,
      end: `${yearAndMonth}-19`,
      className: "bg-red",
      allDay: true
    },

    {
      title: "Black Friday",
      start: `${yearAndMonth}-23`,
      end: `${yearAndMonth}-23`,
      className: "bg-blue",
      allDay: true
    },

    {
      title: "Cyber Week",
      start: `${yearAndMonth}-02`,
      end: `${yearAndMonth}-02`,
      className: "bg-yellow",
      allDay: true
    }
  ];
  let showAddModal = false;
  let showEditModal = false;
  let model = {
    title: "",
    className: "bg-default",
    description:
      "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    start: "",
    end: ""
  };
  let eventColors = [
    "bg-info",
    "bg-orange",
    "bg-red",
    "bg-green",
    "bg-default",
    "bg-blue",
    "bg-purple",
    "bg-yellow"
  ];
  let calendarRef = "";
  function calendarApi() {
    return calendarRef.getAPI();
  }

  function changeView(viewType) {
    defaultView = viewType;
    calendarApi().changeView(viewType);
  }

  function next() {
    calendarApi().next();
  }

  function prev() {
    calendarApi().prev();
  }

  function onDateClick({ date }) {
    showAddModal = true;
    let y = date.getFullYear();
    let m = date.getMonth();
    let d = date.getDate();
    let eventDate;
    if (m + 1 < 10 && d < 10) {
      eventDate = `${y}-0${m + 1}-0${d}`;
    } else if (m + 1 >= 10 && d < 10) {
      eventDate = `${y}-${m + 1}-0${d}`;
    } else if (m + 1 < 10 && d >= 10) {
      eventDate = `${y}-0${m + 1}-${d}`;
    } else if (m + 1 >= 10 && d >= 10) {
      eventDate = `${y}-${m + 1}-${d}`;
    }
    model.start = eventDate;
    model.end = eventDate;
  }

  function onEventClick({ event }) {
    let y = event.start.getFullYear();
    let m = event.start.getMonth();
    let d = event.start.getDate();
    let eventDate;
    if (m + 1 < 10 && d < 10) {
      eventDate = `${y}-0${m + 1}-0${d}`;
    } else if (m + 1 >= 10 && d < 10) {
      eventDate = `${y}-${m + 1}-0${d}`;
    } else if (m + 1 < 10 && d >= 10) {
      eventDate = `${y}-0${m + 1}-${d}`;
    } else if (m + 1 >= 10 && d >= 10) {
      eventDate = `${y}-${m + 1}-${d}`;
    }
    model.start = eventDate;
    model.end = eventDate;
    model = {
      title: event.title,
      className: event.classNames[0],
      start: eventDate,
      end: eventDate,
      description:
        "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
    };
    showEditModal = true;
  }

  function saveEvent() {
    let input = document.getElementById("addEventInput");
    if (input.value !== "") {
      model.title = input.value;
    }
    if (model.title) {
      let event = {
        ...model,
        allDay: true
      };
      events = [
        ...events,
        {
          title: model.title,
          start: model.start,
          end: model.end,
          className: model.className,
          allDay: true
        }
      ];
      model = {
        title: "",
        className: "bg-default",
        start: "",
        end: ""
      };
    }
    showAddModal = false;
  }

  function editEvent() {
    let index = events.findIndex(e => e.title === model.title);
    let event = model;
    let input = document.getElementById("editEventInput");
    let description = document.getElementById("eventDescription");
    if (input.value !== "") {
      event.title = input.value;
    }
    if (description.value !== "") {
      event.description = description.value;
    }
    if (index !== -1) {
      events.splice(index, 1);
    }
    events = [...events, event];
    showEditModal = false;
    model = {
      title: event.title,
      className: "bg-default",
      start: "",
      end: "",
      description:
        "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
    };
  }

  function deleteEvent() {
    let index = events.findIndex(e => e.title === model.title);
    if (index !== -1) {
      events.splice(index, 1);
    }
    events = [...events, {}];
    showEditModal = false;
    model = {
      title: "",
      className: "bg-default",
      start: "",
      end: "",
      description:
        "Nullam id dolor id nibh ultricies vehicula ut id elit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
    };
  }

  function showMe(name) {
    // console.log(name);
  }

  function changeColor(color) {
    model.className = color;
  }
</script>

<div style="transform-origin: center top;">
  <BaseHeader className="pb-6">
    <div class="row align-items-center py-4">
      <div class="col-lg-6 col-7">
        <h6 class="h2 text-white d-inline-block mb-0">{name}</h6>
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
          <RouteBreadcrumb {name} {parent} />
        </nav>
      </div>
      <div class="col-lg-6 mt-3 mt-lg-0 text-lg-right">
        <a
          href="/calendar"
          on:click={next}
          class="fullcalendar-btn-prev btn btn-sm btn-default mr-1">
          <i class="fas fa-angle-left" />
        </a>
        <a
          href="/calendar"
          on:click={prev}
          class="fullcalendar-btn-next btn btn-sm btn-default mr-1">
          <i class="fas fa-angle-right" />
        </a>
        <button
          class="btn btn-sm btn-default {defaultView === 'dayGridMonth' ? 'active' : ''}
          mr-1"
          on:click={() => {
            changeView('dayGridMonth');
          }}>
          Month
        </button>
        <button
          class="btn btn-sm btn-default {defaultView === 'dayGridWeek' ? 'active' : ''}
          mr-1"
          on:click={() => {
            changeView('dayGridWeek');
          }}>
          Week
        </button>
        <button
          class="btn btn-sm btn-default {defaultView === 'timeGridDay' ? 'active' : ''}
          mr-1"
          on:click={() => {
            changeView('timeGridDay');
          }}>
          Day
        </button>
      </div>
    </div>
  </BaseHeader>
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <!-- Fullcalendar -->
        <Card noBody className="card-calendar card">
          <!-- Card header -->
          <div slot="header">
            <!-- Title -->
            <h5 class="h3 mb-0">Calendar</h5>
          </div>
          <!-- Card body -->
          <div class="card-body p-0 card-calendar-body">
            <FullCalendar
              bind:this={calendarRef}
              {events}
              defaultDate={today}
              plugins={calendarPlugins}
              editable="true"
              contentHeight="auto"
              theme="false"
              selectable="true"
              selectHelper="true"
              ref="fullCalendar"
              class="calendar"
              on:dateClick={event => onDateClick(event.detail)}
              on:eventClick={event => onEventClick(event.detail)}
              {defaultView} />
          </div>
        </Card>
      </div>
    </div>
  </div>

  <Modal show={showAddModal} modalClasses="modal-secondary">
    <form class="new-event--form" on:submit={saveEvent}>
      <BaseInput
        label="Event title"
        placeholder="Event title"
        model="title"
        id="addEventInput"
        inputClasses="form-control-alternative new-event--title" />
      <div class="form-group">
        <label class="form-control-label d-block mb-3">Status color</label>
        <div class="btn-group btn-group-toggle btn-group-colors event-tag">
          {#each eventColors as color}
            <label
              key={color}
              class="btn {color}
              {model.className === color ? 'active focused' : ''}">
              <input
                type="radio"
                model={model.className}
                name="event-tag"
                value={color}
                on:click={() => changeColor(color)}
                autocomplete="off" />
            </label>
          {/each}
        </div>
      </div>
      <input type="hidden" class="new-event--start" />
      <input type="hidden" class="new-event--end" />
    </form>
    <div slot="footer" class="w-100 d-flex">
      <BaseButton
        type="primary"
        className="new-event--add mr-auto"
        on:click={saveEvent}>
        Add event
      </BaseButton>
      <BaseButton
        type="link"
        className="ml-auto"
        on:click={() => {
          showAddModal = false;
        }}>
        Close
      </BaseButton>
    </div>
  </Modal>

  <Modal show={showEditModal} modalClasses="modal-secondary">
    <form class="edit-event--form" on:submit={editEvent}>
      <BaseInput
        label="Event title"
        placeholder="Event title"
        model={model.title}
        id="editEventInput"
        value={model.title}
        inputClasses="form-control-alternative new-event--title" />
      <div class="form-group">
        <label class="form-control-label d-block mb-3">Status color</label>
        <div class="btn-group btn-group-toggle btn-group-colors event-tag">
          {#each eventColors as color}
            <label
              key={color}
              class="btn {color}
              {model.className === color ? 'active focused' : ''}">
              <input
                model={model.className}
                on:click={() => changeColor(color)}
                type="radio"
                name="event-tag"
                value={color}
                autocomplete="off" />
            </label>
          {/each}
        </div>
      </div>
      <BaseInput label="Description">
        <textarea
          model={model.description}
          class="form-control form-control-alternative edit-event--description
          textarea-autosize"
          id="eventDescription"
          value={model.description}
          placeholder="Event Desctiption" />
        <i class="form-group--bar" />
      </BaseInput>
      <input type="hidden" class="new-event--start" />
      <input type="hidden" class="new-event--end" />
    </form>

    <div slot="footer" class="w-100 d-flex">
      <BaseButton
        nativeType="submit"
        type="primary"
        className="new-event--add"
        on:click={editEvent}>
        Update
      </BaseButton>
      <BaseButton type="danger" on:click={deleteEvent} className="mr-auto">
        Delete
      </BaseButton>
      <BaseButton
        type="link"
        class="ml-auto"
        on:click={() => {
          showEditModal = false;
        }}>
        Close
      </BaseButton>
    </div>
  </Modal>
</div>
