// extracted_templates/vue-laravel/vue-black-dashboard-pro-laravel-master/vue-black-dashboard-pro-laravel-master/vue-black-dashboard-pro/src/pages/Layout/ContentFooter.vue
<template>
  <footer class="footer">
    <div class="container-fluid">
      <ul class="nav">
        <!-- <li class="nav-item">
            <a href="https://www.creative-tim.com" class="nav-link" target="_blank" rel="noopener">CREATIVE TIM</a>
          </li>
          <li  class="nav-item">
            <a href="https://www.updivision.com" class="nav-link" target="_blank" rel="noopener">UPDIVISION</a>
          </li> -->
        <li class="nav-item">
          <a
            href="https://www.creative-tim.com/presentation"
            class="nav-link"
            target="_blank"
            rel="noopener"
            >ABOUT US</a
          >
        </li>
        <li class="nav-item">
          <a
            href="https://blog.creative-tim.com"
            class="nav-link"
            target="_blank"
            rel="noopener"
            >BLOG</a
          >
        </li>
        <li class="nav-item">
          <a
            href="https://www.creative-tim.com/license"
            class="nav-link"
            target="_blank"
            rel="noopener"
            >LICENSES</a
          >
        </li>
      </ul>
      <div class="copyright">
        <i class="fa fa-copyright" style="font-weight: 200"></i> {{ year }},
        made with <i class="tim-icons icon-heart-2"></i> by
        <a href="https://www.creative-tim.com" target="_blank" rel="noopener"
          >Creative Tim</a
        >
        and
        <a
          href="https://www.updivision.com"
          class="font-weight-bold ml-1"
          target="_blank"
          rel="noopener"
          >UPDIVISION</a
        >
        for a better web.
      </div>
    </div>
  </footer>
</template>
<script>
export default {
  data() {
    return {
      year: new Date().getFullYear(),
    };
  },
};
</script>
<style></style>

// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/ContentFooter.svelte
<script>
  let year = new Date().getFullYear();
</script>

<footer class="footer px-4 mx-2">
  <div class="row align-items-center justify-content-lg-between">
    <div class="col-lg-6">
      <div class="copyright text-center text-lg-left text-muted">
        @ {year}
        <a
          href="https://www.creative-tim.com"
          class="font-weight-bold ml-1"
          target="_blank">
          Creative Tim
        </a>
      </div>
    </div>
    <div class="col-lg-6">
      <ul class="justify-content-center nav nav-footer justify-content-lg-end">
        <li class="nav-item">
          <a href="https://www.creative-tim.com" target="_blank" class="nav-link">
            Creative Tim
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.creative-tim.com/presentation" target="_blank" class="nav-link">
            About Us
          </a>
        </li>
        <li class="nav-item">
          <a href="http://blog.creative-tim.com" target="_blank" class="nav-link">
            Blog
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.creative-tim.com/license" target="_blank" class="nav-link">
            License
          </a>
        </li>
      </ul>
    </div>
  </div>
</footer>
