// extracted_templates/vue-laravel/creativetimofficial-vue-argon-dashboard-pro-laravel-fd914dc1b5592a1ab5fc7c53e0f906bea8dd3b9e/creativetimofficial-vue-argon-dashboard-pro-laravel-fd914dc1b5592a1ab5fc7c53e0f906bea8dd3b9e/vue-argon-dashboard-laravel-pro/src/App.vue
<!--
=========================================================
* Vue Argon Dashboard 2 PRO - v3.0.0
=========================================================

* Product Page: https://creative-tim.com/product/vue-argon-dashboard-pro
* Copyright 2022 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

<template>
  <div
    v-show="layout === 'landing'"
    class="landing-bg h-100 bg-gradient-primary position-fixed w-100"
  ></div>
  <sidenav v-if="showSidenav" />
  <main class="main-content position-relative max-height-vh-100 h-100">
    <navbar v-if="showNavbar" />
    <router-view />
    <app-footer v-show="showFooter" />
    <configurator
      :class="[showConfig ? 'show' : '', hideConfigButton ? 'd-none' : '']"
    />
  </main>
</template>
<script>
import Sidenav from "./examples/Sidenav";
import Configurator from "@/examples/Configurator.vue";
import Navbar from "@/examples/Navbars/Navbar.vue";
import AppFooter from "@/examples/Footer.vue";
import { mapState } from "vuex";

export default {
  name: "App",
  components: {
    Sidenav,
    Configurator,
    Navbar,
    AppFooter
  },
  computed: {
    ...mapState([
      "layout",
      "showSidenav",
      "showNavbar",
      "showFooter",
      "showConfig",
      "hideConfigButton"
    ])
  }
};
</script>

// extracted_templates/react/argon-dashboard-chakra-pro-main-2.0.0/argon-dashboard-chakra-pro-main/src/App.js
/** 

=========================================================
* Vision UI PRO React - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/vision-ui-dashboard-pro-react
* Copyright 2021 Creative Tim (https://www.creative-tim.com/)

* Design and Coded by Simmmple & Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Visionware.

*/
import { Routes, Route, Navigate } from 'react-router-dom'; 

import AuthLayout from "layouts/Auth.js";
import AdminLayout from "layouts/Admin.js";
import RTLLayout from "layouts/RTL.js";
import LandingLayout from "layouts/Landing";
import theme from './theme/theme';   
import {
  ChakraProvider, 
} from '@chakra-ui/react'; 
// Chakra imports

export default function Main() { 
  return (
    <ChakraProvider theme={theme}>
      <Routes>
        <Route path="auth/*" element={<AuthLayout />} />
        <Route
          path="admin/*"
          element={
            <AdminLayout />
          }
        />
        <Route
          path="landing/*"
          element={
            <LandingLayout />
          }
        /> 
        <Route
          path="rtl/*"
          element={
            <RTLLayout  />
          }
        />
        <Route path="/" element={<Navigate to="/admin" replace />} />


  
      </Routes>
    </ChakraProvider>
  );
}
