// extracted_templates/nuxtjs/nuxt-argon-dashboard-2-pro-v2.1.1/nuxt-argon-dashboard-2-pro-v2.1.1/app.vue
<!--
=========================================================
* Nuxt Argon Dashboard 2 PRO - v2.1.1
=========================================================
* Product Page: https://creative-tim.com/product/nuxt-argon-dashboard-pro
* Copyright 2024 Creative Tim (https://www.creative-tim.com)
Coded by www.creative-tim.com
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
<script setup>
import { watch } from "vue";
import { useWindowSize } from "@vueuse/core";
import { useAppStore } from "~/stores/AppStore";

const store = useAppStore();

const { width } = useWindowSize();

watch(width, (newVal) => {
  if (newVal < 1200) {
    const sidebar = document.querySelector(".g-sidenav-show");
    if (sidebar.classList.contains("g-sidenav-pinned")) {
      sidebar.classList.remove("g-sidenav-pinned");
      sidebar.classList.add("g-sidenav-hidden");
      store.pinSidebar = false;
    }
  }
});
</script>

// extracted_templates/react/argon-dashboard-chakra-pro-main-2.0.0/argon-dashboard-chakra-pro-main/src/App.js
/** 

=========================================================
* Vision UI PRO React - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/vision-ui-dashboard-pro-react
* Copyright 2021 Creative Tim (https://www.creative-tim.com/)

* Design and Coded by Simmmple & Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Visionware.

*/
import { Routes, Route, Navigate } from 'react-router-dom'; 

import AuthLayout from "layouts/Auth.js";
import AdminLayout from "layouts/Admin.js";
import RTLLayout from "layouts/RTL.js";
import LandingLayout from "layouts/Landing";
import theme from './theme/theme';   
import {
  ChakraProvider, 
} from '@chakra-ui/react'; 
// Chakra imports

export default function Main() { 
  return (
    <ChakraProvider theme={theme}>
      <Routes>
        <Route path="auth/*" element={<AuthLayout />} />
        <Route
          path="admin/*"
          element={
            <AdminLayout />
          }
        />
        <Route
          path="landing/*"
          element={
            <LandingLayout />
          }
        /> 
        <Route
          path="rtl/*"
          element={
            <RTLLayout  />
          }
        />
        <Route path="/" element={<Navigate to="/admin" replace />} />


  
      </Routes>
    </ChakraProvider>
  );
}
