// extracted_templates/angular/argon-design-system-pro-angular-v1.4.0/argon-design-system-pro-angular-v1.4.0/src/main.ts
/*!

 =========================================================
 * Argon Desing System PRO Angular - v1.4.0
 =========================================================

 * Product Page: https://www.creative-tim.com/product/argon-design-system-pro-angular
 * Copyright 2021 Creative Tim (http://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

 */
import { enableProdMode } from "@angular/core";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";

import { AppModule } from "./app/app.module";
import { environment } from "./environments/environment";

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch(err => console.error(err));

// extracted_templates/react/argon-dashboard-chakra-pro-main-2.0.0/argon-dashboard-chakra-pro-main/src/index.js
/*!

=========================================================
* Vision UI PRO Chakra - v2.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/vision-ui-dashboard-pro-chakra
* Copyright 2021 Creative Tim (https://www.creative-tim.com/)

* Design and Coded by Simmmple & Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/ 

import React from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom"; 
import App from "./App"; // Ensure correct relative path if App is in the same directory 

const container = document.getElementById("root");
const root = createRoot(container);

root.render(
  <BrowserRouter> 
      <App /> 
  </BrowserRouter>
);
