// extracted_templates/vue/vue-argon-dashboard-pro-bs4-v2.0.2/vue-argon-dashboard-pro-bs4-v2.0.2/src/views/Tables/PaginatedTables.vue
<template>
  <div class="content">
    <base-header class="pb-6">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Paginated tables</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <route-bread-crumb></route-bread-crumb>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <base-button size="sm" type="neutral">New</base-button>
          <base-button size="sm" type="neutral">Filters</base-button>
        </div>
      </div>
    </base-header>
    <div class="container-fluid mt--6">
      <div>
        <card
          class="no-border-card"
          body-classes="px-0 pb-1"
          footer-classes="pb-2"
        >
          <template v-slot:header>
            <h3 class="mb-0">Paginated tables</h3>
            <p class="text-sm mb-0">
              This is a client side example of paginated tables using element-ui
              tables.
            </p>
          </template>
          <div>
            <div
              class="col-12 d-flex justify-content-center justify-content-sm-between flex-wrap"
            >
              <el-select
                class="select-primary pagination-select"
                v-model="pagination.perPage"
                placeholder="Per page"
              >
                <el-option
                  class="select-primary"
                  v-for="item in pagination.perPageOptions"
                  :key="item"
                  :label="item"
                  :value="item"
                >
                </el-option>
              </el-select>

              <div>
                <el-input
                  type="search"
                  class="mb-3"
                  clearable
                  prefix-icon="el-icon-search"
                  style="width: 200px"
                  placeholder="Search records"
                  v-model="searchQuery"
                  aria-controls="datatables"
                >
                </el-input>
              </div>
            </div>
            <el-table
              :data="queriedData"
              row-key="id"
              header-row-class-name="thead-light"
              @selection-change="selectionChange"
            >
              <el-table-column
                v-for="column in tableColumns"
                :key="column.label"
                v-bind="column"
              >
              </el-table-column>
              <el-table-column min-width="180px" align="right" label="Actions">
                <template v-slot:default="props">
                  <div class="d-flex">
                    <base-button
                      @click="handleLike(props.$index, props.row)"
                      class="like btn-link"
                      type="info"
                      size="sm"
                      icon
                    >
                      <i class="text-white ni ni-like-2"></i>
                    </base-button>
                    <base-button
                      @click="handleEdit(props.$index, props.row)"
                      class="edit"
                      type="warning"
                      size="sm"
                      icon
                    >
                      <i class="text-white ni ni-ruler-pencil"></i>
                    </base-button>
                    <base-button
                      @click="handleDelete(props.$index, props.row)"
                      class="remove btn-link"
                      type="danger"
                      size="sm"
                      icon
                    >
                      <i class="text-white ni ni-fat-remove"></i>
                    </base-button>
                  </div>
                </template>
              </el-table-column>
            </el-table>
          </div>
          <template v-slot:footer>
            <div
              class="col-12 d-flex justify-content-center justify-content-sm-between flex-wrap"
            >
              <div class="">
                <p class="card-category">
                  Showing {{ from + 1 }} to {{ to }} of {{ total }} entries
                </p>
              </div>
              <base-pagination
                class="pagination-no-border"
                v-model="pagination.currentPage"
                :per-page="pagination.perPage"
                :total="total"
              >
              </base-pagination>
            </div>
          </template>
        </card>
      </div>
    </div>
  </div>
</template>
<script>
import {
  ElTable,
  ElTableColumn,
  ElSelect,
  ElOption,
  ElInput,
} from "element-plus";
import RouteBreadCrumb from "@/components/Breadcrumb/RouteBreadcrumb";
import BasePagination from "@/components/BasePagination";
import swal from "sweetalert2";
import users from "./users2";

export default {
  components: {
    BasePagination,
    RouteBreadCrumb,
    [ElSelect.name]: ElSelect,
    [ElOption.name]: ElOption,
    [ElTable.name]: ElTable,
    [ElInput.name]: ElInput,
    [ElTableColumn.name]: ElTableColumn,
  },
  computed: {
    pagedData() {
      return this.tableData.slice(this.from, this.to);
    },
    /***
     * Searches through table data and returns a paginated array.
     * Note that this should not be used for table with a lot of data as it might be slow!
     * Do the search and the pagination on the server and display the data retrieved from server instead.
     * @returns {computed.pagedData}
     */
    queriedData() {
      if (!this.searchQuery) {
        return this.pagedData;
      }
      let result = this.tableData.filter((row) => {
        let isIncluded = false;
        for (let key of this.propsToSearch) {
          let rowValue = row[key].toString();
          if (rowValue.includes && rowValue.includes(this.searchQuery)) {
            isIncluded = true;
          }
        }
        return isIncluded;
      });

      return result.slice(this.from, this.to);
    },
    to() {
      let highBound = this.from + this.pagination.perPage;
      if (this.total < highBound) {
        highBound = this.total;
      }
      return highBound;
    },
    from() {
      return this.pagination.perPage * (this.pagination.currentPage - 1);
    },
    total() {
      return this.searchedData.length > 0
        ? this.searchedData.length
        : this.tableData.length;
    },
  },
  data() {
    return {
      pagination: {
        perPage: 5,
        currentPage: 1,
        perPageOptions: [5, 10, 25, 50],
        total: 0,
      },
      searchQuery: "",
      propsToSearch: ["name", "email"],
      tableColumns: [
        {
          type: "selection",
        },
        {
          prop: "name",
          label: "Name",
          minWidth: 200,
        },
        {
          prop: "email",
          label: "Email",
          minWidth: 250,
        },
        {
          prop: "age",
          label: "Age",
          minWidth: 100,
        },
        {
          prop: "salary",
          label: "Salary",
          minWidth: 120,
        },
      ],
      // tableColumns: [
      //   {
      //     type: "selection",
      //   },
      //   {
      //     prop: "name",
      //     label: "Name",
      //     minWidth: 160,
      //     sortable: true,
      //   },
      //   {
      //     prop: "position",
      //     label: "Position",
      //     minWidth: 220,
      //     sortable: true,
      //   },
      //   {
      //     prop: "city",
      //     label: "Office",
      //     minWidth: 135,
      //     sortable: true,
      //   },
      //   {
      //     prop: "age",
      //     label: "Age",
      //     minWidth: 100,
      //     sortable: true,
      //   },
      //   {
      //     prop: "createdAt",
      //     label: "Start Date",
      //     minWidth: 150,
      //     sortable: true,
      //   },
      //   {
      //     prop: "salary",
      //     label: "Salary",
      //     minWidth: 120,
      //     sortable: true,
      //   },
      // ],
      tableData: users,
      searchedData: [],
    };
  },
  methods: {
    handleLike(index, row) {
      const swalWithBootstrapButtons1 = swal.mixin({
        customClass: {
          confirmButton: "btn btn-success btn-fill",
        },
        buttonsStyling: false,
      });

      swalWithBootstrapButtons1.fire({
        title: `You liked ${row.name}`,
      });
    },
    handleEdit(index, row) {
      const swalWithBootstrapButtons2 = swal.mixin({
        customClass: {
          confirmButton: "btn btn-info btn-fill",
        },
        buttonsStyling: false,
      });

      swalWithBootstrapButtons2.fire({
        title: `You want to edit ${row.name}`,
      });
    },
    handleDelete(index, row) {
      const swalWithBootstrapButtons3 = swal.mixin({
        customClass: {
          confirmButton: "btn btn-success btn-fill",
          cancelButton: "btn btn-danger btn-fill",
        },
        buttonsStyling: false,
      });
      swalWithBootstrapButtons3
        .fire({
          title: "Are you sure?",
          text: `You won't be able to revert this!`,
          showCancelButton: true,
          confirmButtonText: "Yes, delete it!",
        })
        .then((result) => {
          if (result.value) {
            this.deleteRow(row);
            swalWithBootstrapButtons3.fire({
              title: "Deleted!",
              text: `You deleted ${row.name}`,
            });
          }
        });
    },
    deleteRow(row) {
      let indexToDelete = this.tableData.findIndex(
        (tableRow) => tableRow.id === row.id
      );
      if (indexToDelete >= 0) {
        this.tableData.splice(indexToDelete, 1);
      }
    },
    selectionChange(selectedRows) {
      this.selectedRows = selectedRows;
    },
  },
};
</script>
<style>
.no-border-card .card-footer {
  border-top: 0;
}
</style>

// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/Tables/paginatedTables.svelte
<script>
  import { fade } from "svelte/transition";
  import RouteBreadcrumb from "../../../components/Breadcrumb/RouteBreadcrumb.svelte";
  import BaseHeader from "../../../components/BaseHeader.svelte";
  import BaseButton from "../../../components/BaseButton.svelte";
  import Card from "../../../components/Cards/Card.svelte";
  import BaseCheckbox from "../../../components/Inputs/BaseCheckbox.svelte";
  import clientPaginationMixin from "./PaginatedTables/clientPaginationMixin";
  import Swal from "sweetalert2/dist/sweetalert2.js";
  import users from "./users2";
  export let name = "Paginated tables";
  import { onMount } from "svelte";
  import jQuery from "jquery";
  import "datatables.net-dt/css";
  import dt from "datatables.net";
  import dtCss from "datatables.net-dt";
  import { clickOutside } from "../../../components/clickOutside.js";
  let search = false;
  let currentPage = 1;
  dt(jQuery);
  let tableElement;
  let table;
  let suffix = false;
  let lengthMenu = [5, 10, 15, 50];
  let perPage = 10;
  let total = users.length;
  let info;
  onMount(
    () =>
      (table = jQuery(tableElement).DataTable({
        order: [[1, "asc"]],
        paging: true,
        searching: true,
        ordering: true,
        info: true,
        responsive: true,
        autoWidth: false,
        lengthMenu: [5, 10, 25, 50],
        pageLength: perPage
      })),
    function() {
      let topmenu = document.getElementsByTagName("nav").item(0);
      topmenu.classList.add("bg-danger");
      topmenu.classList.add("navbar-dark");
      topmenu.classList.remove("navbar-light");
      let search = document.getElementsByTagName("form").item(0);
      search.classList.remove("navbar-search-dark");
      search.classList.add("navbar-search-light");
    }
  );

  let mixins = clientPaginationMixin;
  let propsToSearch = ["name", "email", "age"];
  let tableColumns = [
    {
      type: "selection"
    },
    {
      prop: "name",
      label: "Name",
      minWidth: 160,
      sortable: true
    },
    {
      prop: "position",
      label: "Position",
      minWidth: 220,
      sortable: true
    },
    {
      prop: "city",
      label: "Office",
      minWidth: 135,
      sortable: true
    },
    {
      prop: "age",
      label: "Age",
      minWidth: 100,
      sortable: true
    },
    {
      prop: "createdAt",
      label: "Start Date",
      minWidth: 150,
      sortable: true
    },
    {
      prop: "salary",
      label: "Salary",
      minWidth: 120,
      sortable: true
    }
  ];
  let tableData = users;
  let selectedRows = [];

  function paginationChange(page) {
    pagination.currentPage = page;
  }

  function handleLike(index, row) {
    Swal.fire({
      title: `you like ${row.name}`,
      buttonStyling: false,
      type: "succes",
      confirmButtonClass: "btn btn-success btn-fill"
    });
  }
  function handleEdit(index, row) {
    Swal.fire({
      title: `You want to edit ${row.name}`,
      buttonsStyling: false,
      confirmButtonClass: "btn btn-info btn-fill"
    });
  }
  function handleDelete(index, row) {
    Swal.fire({
      title: "Are you sure?",
      text: `You won't be able to revert this!`,
      type: "warning",
      showCancelButton: true,
      confirmButtonClass: "btn btn-success btn-fill",
      cancelButtonClass: "btn btn-danger btn-fill",
      confirmButtonText: "Yes, delete it!",
      buttonsStyling: false
    }).then(result => {
      if (result.value) {
        deleteRow(row);
        Swal.fire({
          title: "Deleted!",
          text: `You deleted ${row.name}`,
          type: "success",
          confirmButtonClass: "btn btn-success btn-fill",
          buttonsStyling: false
        });
      }
    });
  }
  function deleteRow(row) {
    let indexToDelete = tableData.findIndex(tableRow => tableRow.id === row.id);
    if (indexToDelete >= 0) {
      tableData.splice(indexToDelete, 1);
    }
  }
  function selectionChange(selectedRows) {
    selectedRows = selectedRows;
  }

  function tableShow(item) {
    table.page.len(item).draw();
    perPage = item;
    suffix = false;
  }

  function handleClickOutside(event) {
    suffix = false;
  }
</script>

<style>
  input#searchTable:focus,
  input#searchTable:active,
  input#searchTable:focus:active,
  input#searchTable:active:focus {
    transition: all 0.2s ease-in-out;
  }

  .thead-light {
    background: #f6f9fc;
    color: #8898aa;
    font-size: 0.65rem !important;
    text-transform: uppercase !important;
    letter-spacing: 1px !important;
    border-top: 1px solid #ebeef5;
  }

  tbody tr {
    border-top: 1px solid #ebeef5;
  }

  thead tr td {
    padding-top: 0px;
    padding-bottom: 0px;
    padding-left: 1.5rem;
    padding-right: 1.5rem;
    width: auto;
    min-width: auto;
    white-space: nowrap;
  }

  table tbody tr {
    transition: all 0.3s ease-in-out;
  }

  table tbody tr:hover {
    background-color: transparent !important;
    transition: all 0.3s ease-in-out;
  }

  table tbody tr td {
    width: auto;
    min-width: auto;
    white-space: nowrap;
    box-sizing: border-box;
    white-space: normal;
    word-break: break-all;
    line-height: 23px;
    text-align: left;
    color: #525f7f;
    font-size: 0.8125rem;
    white-space: nowrap;
  }

  table.paginatedTable thead tr {
    border-bottom: 1px solid #ebeef5;
    border-top: 1px solid #ebeef5;
  }

  table.paginatedTable thead tr th,
  table.paginatedTable thead tr td {
    min-height: 40px;
    height: 40px;
    border-bottom: 1px solid #ebeef5;
    border-top: 1px solid #ebeef5;
  }

  table.paginatedTable tbody tr td,
  table.paginatedTable tbody tr th {
    min-height: 40px;
    height: 40px;
  }

  .tdPaginated {
    padding-left: 1.5rem;
    padding-right: 1.5rem;
    padding-top: 1rem;
    padding-bottom: 1rem;
  }

  tbody.tbodyPaginated tr.trPaginated td {
    border-bottom: 1px solid #ebeef5;
  }
</style>

<div class="content" transition:fade={{ duration: 250 }}>
  <BaseHeader className="pb-6">
    <div class="row align-items-center py-4">
      <div class="col-7 col-lg-6">
        <h6 class="h2 text-white d-inline-block mb-0">Paginated tables</h6>
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
          <RouteBreadcrumb {name} />
        </nav>
      </div>
      <div class="col-5 col-lg-6 text-right">
        <BaseButton size="sm" type="neutral">New</BaseButton>
        <BaseButton size="sm" type="neutral">Filters</BaseButton>
      </div>
    </div>
  </BaseHeader>
  <div class="container-fluid mt--6">
    <div>
      <Card
        className="no-border-card"
        bodyClasses="px-0 pb-1"
        footerClasses="pb-2">
        <div slot="header">
          <h3 class="mb-0">Paginated tables</h3>
          <p class="text-sm mb-0">
            This is a client side example of paginated tables using element-ui
            tables.
          </p>
        </div>
        <div>
          <div
            class="col-12 d-flex justify-content-center
            justify-content-sm-between flex-wrap px-0">
            <div
              class="el-select select-primary pagination-select"
              use:clickOutside
              on:click_outside={handleClickOutside}
              style="padding-left: 15px;">
              <!---->
              <div
                class="el-input el-input--suffix {suffix === true ? 'is-focus' : ''}">
                <!---->
                <input
                  type="text"
                  id="search"
                  on:click={() => (suffix = true)}
                  readonly="readonly"
                  autocomplete="off"
                  placeholder={perPage}
                  class="el-input__inner text-dark" />
                <!---->
                <span class="el-input__suffix">
                  <span class="el-input__suffix-inner">
                    <i
                      class="el-select__caret el-input__icon el-icon-arrow-up {suffix === true ? 'is-reverse' : ''}" />
                    <!---->
                    <!---->
                  </span>
                  <!---->
                </span>
                <!---->
              </div>
              <div
                class="el-select-dropdown el-popper"
                style="display: {suffix === false ? 'none' : ''}; min-width:
                210px;">
                <div class="el-scrollbar" style="">
                  <div
                    class="el-select-dropdown__wrap el-scrollbar__wrap"
                    style="margin-bottom: -17px; margin-right: -17px;">
                    <ul class="el-scrollbar__view el-select-dropdown__list">
                      <!---->
                      {#each lengthMenu as item}
                        <li
                          class="el-select-dropdown__item select-primary {perPage === item ? 'selected' : ''}"
                          on:click={() => tableShow(item)}>
                          <span>{item}</span>
                        </li>
                      {/each}
                    </ul>
                  </div>
                  <div class="el-scrollbar__bar is-horizontal">
                    <div
                      class="el-scrollbar__thumb"
                      style="transform: translateX(0%);" />
                  </div>
                  <div class="el-scrollbar__bar is-vertical">
                    <div
                      class="el-scrollbar__thumb"
                      style="transform: translateY(0%);" />
                  </div>
                </div>
                <!---->
              </div>
            </div>
            <div style="padding-right: 15px;">
              <span placeholder="Search...">
                <div class="form-group">
                  <!---->
                  <div class="input-group {search == true ? 'focused' : ''}">
                    <div class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="fas fa-search" />
                      </span>
                    </div>
                    <input
                      on:focus={() => (search = true)}
                      on:blur={() => (search = false)}
                      type="text"
                      placeholder="Search..."
                      on:keyup={table.search(this.value).draw()}
                      id="searchTable"
                      class="form-control"
                      valid="true" />
                    <!---->
                  </div>
                  <div class="valid-feedback" />
                  <!---->
                </div>
              </span>
            </div>
            <table
              bind:this={tableElement}
              class="table-responsive table-flush align-items-center
              border-bottom-0 paginatedTable"
              style="width: 100%">
              <thead class="thead-light">
                <tr>
                  <th
                    class="py-0 pr-0 text-left"
                    style="min-width: 48px; width: 5%; padding-left: 1.5rem;">
                    <BaseCheckbox />
                  </th>
                  {#each tableColumns as column, i}
                    {#if i !== 0}
                      <th
                        class="py-0 {i === 1 ? 'pl-0 text-left' : ''}"
                        style="min-width: {column.minWidth}px; width: 10%;">
                        {column.label}
                        <span class="caret-wrapper">
                          <i class="sort-caret ascending" />
                          <i class="sort-caret descending" />
                        </span>
                      </th>
                    {/if}
                  {/each}
                  <th class="py-0" style="width: 15%;">Actions</th>
                </tr>
              </thead>
              <tbody class="tbodyPaginated">
                {#each tableData as user, i}
                  <tr class="trPaginated">
                    <td
                      colspan="1"
                      rowspan="1"
                      class="tdPaginated pr-0 text-left">
                      <BaseCheckbox />
                    </td>
                    <td
                      colspan="1"
                      rowspan="1"
                      class="tdPaginated pl-0 text-left">
                      {user.name}
                    </td>
                    <td colspan="1" rowspan="1" class="tdPaginated">
                      {user.position}
                    </td>
                    <td colspan="1" rowspan="1" class="tdPaginated">
                      {user.city}
                    </td>
                    <td colspan="1" rowspan="1" class="tdPaginated">
                      {user.age}
                    </td>
                    <td colspan="1" rowspan="1" class="tdPaginated">
                      {user.createdAt}
                    </td>
                    <td colspan="1" rowspan="1" class="tdPaginated">
                      {user.salary}
                    </td>
                    <td colspan="1" rowspan="1" class="tdPaginated">
                      <BaseButton
                        className="like btn-link"
                        type="info"
                        size="sm"
                        on:click={() => handleLike(i, user)}
                        icon>
                        <i class="text-white ni ni-like-2" />
                      </BaseButton>
                      <BaseButton
                        className="edit"
                        type="warning"
                        size="sm"
                        on:click={() => handleEdit(i, user)}
                        icon>
                        <i class="text-white ni ni-ruler-pencil" />
                      </BaseButton>
                      <BaseButton
                        className="remove btn-link"
                        type="danger"
                        size="sm"
                        on:click={() => handleDelete(i, user)}
                        icon>
                        <i class="text-white ni ni-fat-remove" />
                      </BaseButton>
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        </div>
      </Card>
    </div>
  </div>
</div>
