// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/ContentFooter.svelte
<script>
  let year = new Date().getFullYear();
</script>

<footer class="footer px-4 mx-2">
  <div class="row align-items-center justify-content-lg-between">
    <div class="col-lg-6">
      <div class="copyright text-center text-lg-left text-muted">
        @ {year}
        <a
          href="https://www.creative-tim.com"
          class="font-weight-bold ml-1"
          target="_blank">
          Creative Tim
        </a>
      </div>
    </div>
    <div class="col-lg-6">
      <ul class="justify-content-center nav nav-footer justify-content-lg-end">
        <li class="nav-item">
          <a href="https://www.creative-tim.com" target="_blank" class="nav-link">
            Creative Tim
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.creative-tim.com/presentation" target="_blank" class="nav-link">
            About Us
          </a>
        </li>
        <li class="nav-item">
          <a href="http://blog.creative-tim.com" target="_blank" class="nav-link">
            Blog
          </a>
        </li>
        <li class="nav-item">
          <a href="https://www.creative-tim.com/license" target="_blank" class="nav-link">
            License
          </a>
        </li>
      </ul>
    </div>
  </div>
</footer>

// extracted_templates/vue/vue-now-ui-dashboard-pro-v2.2.0/vue-now-ui-dashboard-pro-v2.2.0/src/views/dashboard/layout/ContentFooter.vue
<template>
  <footer class="footer">
    <div class="container-fluid d-flex flex-wrap justify-content-between">
      <nav>
        <ul class="footer-menu">
          <li>
            <router-link :to="{ path: '/dashboard' }">Dashboard</router-link>
          </li>
        </ul>
      </nav>
      <div class="copyright">
        &copy; {{ year }}, Designed by
        <a href="https://www.invisionapp.com/">Invision</a>. Coded by
        <a
          href="https://www.creative-tim.com/?ref=pdf-vuejs"
          target="_blank"
          rel="noopener"
          >Creative Tim</a
        >.
      </div>
    </div>
  </footer>
</template>
<script>
export default {
  data() {
    return {
      year: new Date().getFullYear(),
    };
  },
};
</script>
<style></style>
