// extracted_templates/vue/vue-now-ui-dashboard-pro-v2.2.0/vue-now-ui-dashboard-pro-v2.2.0/src/views/dashboard/forms/RegularForms.vue
<template>
  <div class="row">
    <div class="col-md-6">
      <vnud-card class="stacked-form" title="Stacked Form">
        <template v-slot:header>
          <h4 class="card-title">Stacked Form</h4>
        </template>

        <form method="#" action="#" @submit.prevent>
          <div>
            <fg-input
              label="Email address"
              type="email"
              placeholder="Enter email"
            >
            </fg-input>
            <fg-input label="Password" type="password" placeholder="Password">
            </fg-input>
            <div class="form-group">
              <checkbox>Subscribe to newsletter</checkbox>
            </div>
            <n-button type="primary">Submit</n-button>
          </div>
        </form>
      </vnud-card>
    </div>
    <div class="col-md-6">
      <vnud-card title="Horizontal Form">
        <template v-slot:header>
          <h4 class="card-title">Horizontal Form</h4>
        </template>

        <form class="form-horizontal" action="#" method="#" @submit.prevent>
          <div class="row">
            <label class="col-md-3 col-form-label">Username</label>
            <div class="col-md-9">
              <fg-input placeholder="Username"> </fg-input>
            </div>
          </div>

          <div class="row">
            <label class="col-md-3 col-form-label">Email</label>
            <div class="col-md-9">
              <fg-input placeholder="Email" type="email"> </fg-input>
            </div>
          </div>

          <div class="row">
            <label class="col-md-3 col-form-label">Password</label>
            <div class="col-md-9">
              <fg-input placeholder="Password" type="password"> </fg-input>
            </div>
          </div>

          <div class="row">
            <label class="col-md-3 col-form-label"></label>
            <div class="col-md-9">
              <checkbox>Remember me</checkbox>
            </div>
          </div>
        </form>
        <div class="row">
          <div class="col-md-9 offset-md-3 col-12">
            <n-button native-type="submit" type="primary"> Sign in </n-button>
          </div>
        </div>
      </vnud-card>
    </div>
    <!-- end card -->
    <div class="col-md-12">
      <vnud-card>
        <template v-slot:header>
          <h4 class="card-title">Form Elements</h4>
        </template>
        <div>
          <form method="get" action="/" class="form-horizontal">
            <div class="row">
              <label class="col-sm-2 col-form-label">With help</label>
              <div class="col-sm-10">
                <fg-input placeholder="Enter email">
                  <template v-slot:helpBlock>
                    <span class="form-text"
                      >A block of help text that breaks onto a new line.
                    </span>
                  </template>
                </fg-input>
              </div>
            </div>

            <div class="row">
              <label class="col-sm-2 col-form-label">Password</label>
              <div class="col-sm-10">
                <fg-input type="password" value="password"> </fg-input>
              </div>
            </div>

            <div class="row">
              <label class="col-sm-2 col-form-label">Placeholder</label>
              <div class="col-sm-10">
                <fg-input placeholder="Placeholder"> </fg-input>
              </div>
            </div>

            <div class="row">
              <label class="col-sm-2 col-form-label">Disabled</label>
              <div class="col-sm-10">
                <fg-input value="Disabled input here.." disabled> </fg-input>
              </div>
            </div>

            <div class="row">
              <label class="col-sm-2 col-form-label">Static Control</label>
              <div class="col-sm-10">
                <fg-input>
                  <p class="form-control-static">hello@creative-tim.com</p>
                </fg-input>
              </div>
            </div>

            <div class="row">
              <label class="col-sm-2 col-form-label"
                >Checkboxes and radios</label
              >
              <div class="col-sm-10 checkbox-radios">
                <checkbox v-model="checkboxes.first">First checkbox</checkbox>
                <checkbox v-model="checkboxes.second">Second checkbox</checkbox>

                <radio name="radio" checked>First Radio</radio>
                <radio name="radio">Second Radio</radio>
              </div>
            </div>

            <div class="row">
              <label class="col-sm-2 col-form-label">Inline checkboxes</label>
              <div class="col-sm-10 checkbox-radios">
                <checkbox v-model="checkboxes.a" inline>a</checkbox>
                <checkbox v-model="checkboxes.b" inline>b</checkbox>
                <checkbox v-model="checkboxes.c" inline>c</checkbox>
              </div>
            </div>
          </form>
        </div>
      </vnud-card>
      <!-- end card -->
    </div>
    <div class="col-md-12">
      <vnud-card>
        <template v-slot:header>
          <h4 class="card-title">Input Variants</h4>
        </template>

        <form method="get" action="/" class="form-horizontal">
          <div class="row">
            <label class="col-sm-2 col-form-label"
              >Custom Checkboxes &amp; radios</label
            >
            <div class="col-sm-4 col-sm-offset-1 checkbox-radios">
              <checkbox v-model="checkboxes.custom1">Unchecked</checkbox>
              <checkbox v-model="checkboxes.custom2">Checked</checkbox>
              <checkbox v-model="checkboxes.custom1" disabled
                >Disabled Checked</checkbox
              >
              <checkbox v-model="checkboxes.custom2" disabled
                >Disabled Checked</checkbox
              >
            </div>

            <div class="col-sm-5 checkbox-radios">
              <radio name="radio1" checked>Radio is On</radio>
              <radio name="radio1">Radio is Off</radio>

              <radio name="radio2" disabled checked>Radio is On</radio>
              <radio name="radio2" disabled>Radio is Off</radio>
            </div>
          </div>

          <div class="row">
            <label class="col-sm-2 col-form-label">Input with success</label>
            <div class="col-sm-10">
              <fg-input is-valid value="Success"></fg-input>
            </div>
          </div>

          <div class="row">
            <label class="col-sm-2 col-form-label">Input with error</label>
            <div class="col-sm-10">
              <fg-input is-error value="Error"></fg-input>
            </div>
          </div>

          <div class="row">
            <label class="col-sm-2 col-form-label">Column sizing</label>

            <div class="col-sm-10">
              <div class="row">
                <div class="col-md-3">
                  <fg-input placeholder=".col-md-3"></fg-input>
                </div>

                <div class="col-md-4">
                  <fg-input placeholder=".col-md-4"></fg-input>
                </div>

                <div class="col-md-5">
                  <fg-input placeholder=".col-md-5"></fg-input>
                </div>
              </div>
            </div>
          </div>
        </form>
      </vnud-card>
    </div>
  </div>
</template>
<script>
import { Checkbox, Radio } from "@/components/index";

export default {
  components: {
    Checkbox,
    Radio,
  },
  data() {
    return {
      checkboxes: {
        custom1: false,
        custom2: true,
        first: true,
        second: false,
        a: false,
        b: false,
        c: false,
        unchecked: false,
        checked: true,
        disabledUnchecked: false,
        disabledChecked: true,
      },
    };
  },
};
</script>
<style></style>

// extracted_templates/react/now-ui-dashboard-pro-react-v1.5.2/now-ui-dashboard-pro-react-v1.5.2/src/views/Forms/RegularForms.js
/*!

=========================================================
* Now UI Dashboard PRO React - v1.5.2
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2023 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";

// reactstrap components
import {
  Button,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  CardTitle,
  Label,
  FormGroup,
  Form,
  Input,
  FormText,
  Row,
  Col,
} from "reactstrap";

// core components
import PanelHeader from "components/PanelHeader/PanelHeader.js";

function RegularForms() {
  return (
    <>
      <PanelHeader size="sm" />
      <div className="content">
        <Row>
          <Col md="6">
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Stacked Form</CardTitle>
              </CardHeader>
              <CardBody>
                <Form action="#" method="#">
                  <label>Email address</label>
                  <FormGroup>
                    <Input type="email" />
                  </FormGroup>
                  <label>Password</label>
                  <FormGroup>
                    <Input type="password" />
                  </FormGroup>
                  <FormGroup check className="mt-3">
                    <Label check>
                      <Input type="checkbox" />
                      <span className="form-check-sign" />
                      Subscribe to newsletter
                    </Label>
                  </FormGroup>
                </Form>
              </CardBody>
              <CardFooter>
                <Button className="btn-fill" color="primary" type="submit">
                  Submit
                </Button>
              </CardFooter>
            </Card>
          </Col>
          <Col md="6">
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Horizontal Form</CardTitle>
              </CardHeader>
              <CardBody>
                <Form className="form-horizontal">
                  <Row>
                    <Label md="3">Username</Label>
                    <Col md="9">
                      <FormGroup>
                        <Input type="text" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label md="3">Email</Label>
                    <Col md="9">
                      <FormGroup>
                        <Input type="email" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label md="3">Password</Label>
                    <Col md="9">
                      <FormGroup>
                        <Input type="password" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Col md="3" />
                    <Col md="9">
                      <FormGroup check>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />
                          Remember me
                        </Label>
                      </FormGroup>
                    </Col>
                  </Row>
                </Form>
              </CardBody>
              <CardFooter>
                <Row>
                  <Col md="3" />
                  <Col md="9">
                    <Button className="btn-fill" color="primary" type="submit">
                      Sign in
                    </Button>
                  </Col>
                </Row>
              </CardFooter>
            </Card>
          </Col>
          <Col md="12">
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Form Elements</CardTitle>
              </CardHeader>
              <CardBody>
                <Form action="/" className="form-horizontal" method="get">
                  <Row>
                    <Label sm="2">With help</Label>
                    <Col sm="10">
                      <FormGroup>
                        <Input type="text" />
                        <FormText color="default" tag="span">
                          A block of help text that breaks onto a new line.
                        </FormText>
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Password</Label>
                    <Col sm="10">
                      <FormGroup>
                        <Input type="password" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Placeholder</Label>
                    <Col sm="10">
                      <FormGroup>
                        <Input placeholder="placeholder" type="text" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Disabled</Label>
                    <Col sm="10">
                      <FormGroup>
                        <Input
                          defaultValue="Disabled input here.."
                          disabled
                          type="text"
                        />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Static control</Label>
                    <Col sm="10">
                      <FormGroup>
                        <p className="form-control-static">
                          hello@creative-tim.com
                        </p>
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Checkboxes and radios</Label>
                    <Col className="checkbox-radios" sm="10">
                      <FormGroup check>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />
                          First Checkbox
                        </Label>
                      </FormGroup>
                      <FormGroup check>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />
                          Second Checkbox
                        </Label>
                      </FormGroup>
                      <FormGroup check className="form-check-radio">
                        <Label check>
                          <Input
                            defaultChecked
                            defaultValue="option1"
                            id="exampleRadios1"
                            name="exampleRadios"
                            type="radio"
                          />
                          <span className="form-check-sign" />
                          First Radio
                        </Label>
                      </FormGroup>
                      <FormGroup check className="form-check-radio">
                        <Label check>
                          <Input
                            defaultValue="option2"
                            id="exampleRadios2"
                            name="exampleRadios"
                            type="radio"
                          />
                          <span className="form-check-sign" />
                          Second Radio
                        </Label>
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Inline checkboxes</Label>
                    <Col sm="10">
                      <FormGroup check inline>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />a
                        </Label>
                      </FormGroup>
                      <FormGroup check inline>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />b
                        </Label>
                      </FormGroup>
                      <FormGroup check inline>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />c
                        </Label>
                      </FormGroup>
                    </Col>
                  </Row>
                </Form>
              </CardBody>
            </Card>
          </Col>
          <Col md="12">
            <Card>
              <CardHeader>
                <CardTitle tag="h4">Input Variants</CardTitle>
              </CardHeader>
              <CardBody>
                <Form action="/" className="form-horizontal" method="get">
                  <Row>
                    <Label sm="2">Custom Checkboxes &amp; radios</Label>
                    <Col className="checkbox-radios" sm={4}>
                      <FormGroup check>
                        <Label check>
                          <Input type="checkbox" />
                          <span className="form-check-sign" />
                          Unchecked
                        </Label>
                      </FormGroup>
                      <FormGroup check>
                        <Label check>
                          <Input defaultChecked type="checkbox" />
                          <span className="form-check-sign" />
                          Checked
                        </Label>
                      </FormGroup>
                      <FormGroup check disabled>
                        <Label check>
                          <Input disabled type="checkbox" />
                          <span className="form-check-sign" />
                          Disabled Unchecked
                        </Label>
                      </FormGroup>
                      <FormGroup check disabled>
                        <Label check>
                          <Input disabled type="checkbox" />
                          <span className="form-check-sign" />
                          Disabled Checked
                        </Label>
                      </FormGroup>
                    </Col>
                    <Col className="checkbox-radios" sm="5">
                      <FormGroup check className="form-check-radio">
                        <Label check>
                          <Input
                            defaultValue="option1"
                            id="exampleRadios3"
                            name="exampleRadio"
                            type="radio"
                          />
                          <span className="form-check-sign" />
                          Radio is off
                        </Label>
                      </FormGroup>
                      <FormGroup check className="form-check-radio">
                        <Label check>
                          <Input
                            defaultChecked
                            defaultValue="option2"
                            id="exampleRadios4"
                            name="exampleRadio"
                            type="radio"
                          />
                          <span className="form-check-sign" />
                          Radio is on
                        </Label>
                      </FormGroup>
                      <FormGroup check className="form-check-radio" disabled>
                        <Label check>
                          <Input
                            defaultValue="option1"
                            disabled
                            id="exampleRadios5"
                            name="exampleRadio1"
                            type="radio"
                          />
                          <span className="form-check-sign" />
                          Radio is off
                        </Label>
                      </FormGroup>
                      <FormGroup check className="form-check-radio" disabled>
                        <Label check>
                          <Input
                            defaultChecked
                            defaultValue="option2"
                            disabled
                            id="exampleRadios6"
                            name="exampleRadio1"
                            type="radio"
                          />
                          <span className="form-check-sign" />
                          Radio is on
                        </Label>
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Input with success</Label>
                    <Col sm="10">
                      <FormGroup className="has-success">
                        <Input defaultValue="Success" type="text" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Input with error</Label>
                    <Col sm="10">
                      <FormGroup className="has-danger">
                        <Input defaultValue="Error" type="text" />
                      </FormGroup>
                    </Col>
                  </Row>
                  <Row>
                    <Label sm="2">Column sizing</Label>
                    <Col sm="10">
                      <Row>
                        <Col md="3">
                          <FormGroup>
                            <Input placeholder="md={3}" type="text" />
                          </FormGroup>
                        </Col>
                        <Col md="4">
                          <FormGroup>
                            <Input placeholder="md={4}" type="text" />
                          </FormGroup>
                        </Col>
                        <Col md="5">
                          <FormGroup>
                            <Input placeholder="md={5}" type="text" />
                          </FormGroup>
                        </Col>
                      </Row>
                    </Col>
                  </Row>
                </Form>
              </CardBody>
            </Card>
          </Col>
        </Row>
      </div>
    </>
  );
}

export default RegularForms;
