// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/components/buttons.svelte
<script>
  import BaseHeader from "../../../components/BaseHeader.svelte";
  import RouteBreadcrumb from "../../../components/Breadcrumb/RouteBreadcrumb.svelte";
  import BaseButton from "../../../components/BaseButton.svelte";
  import Card from "../../../components/Cards/Card.svelte";
  export let name = "Buttons";
  import { fade } from "svelte/transition";
  import { onMount } from "svelte";
  onMount(function() {
    let topmenu = document.getElementsByTagName("nav").item(0);
    topmenu.classList.add("bg-danger");
    topmenu.classList.add("navbar-dark");
    topmenu.classList.remove("navbar-light");
    let search = document.getElementsByTagName("form").item(0);
    search.classList.remove("navbar-search-dark");
    search.classList.add("navbar-search-light");
  });
</script>

<div transition:fade={{ duration: 250 }}>
  <BaseHeader className="pb-6">
    <div class="row align-items-center py-4">
      <div class="col-lg-6 col-7">
        <h6 class="h2 text-white d-inline-block mb-0">{name}</h6>
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
          <RouteBreadcrumb {name} />
        </nav>
      </div>
      <div class="col-lg-6 col-5 text-right">
        <BaseButton size="sm" type="neutral">New</BaseButton>
        <BaseButton size="sm" type="neutral">Filters</BaseButton>
      </div>
    </div>
  </BaseHeader>

  <div class="container-fluid mt--6">
    <div class="row justify-content-center">
      <div class="col-lg-8 card-wrapper ct-example">
        <!-- Styles -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Styles</h3>
          </div>
          <div class="card-body">
            <BaseButton icon type="primary">Button</BaseButton>
            <BaseButton icon type="primary">
              <span class="btn-inner--icon">
                <i class="ni ni-bag-17" />
              </span>
              <span class="btn-inner--text">With icon</span>
            </BaseButton>
            <BaseButton icon type="primary">
              <span class="btn-inner--icon">
                <i class="ni ni-atom" />
              </span>
            </BaseButton>
          </div>
        </Card>
        <!-- Colors -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Colors</h3>
          </div>
          <div class="card-body">
            <BaseButton type="default">Default</BaseButton>
            <BaseButton type="primary">Primary</BaseButton>
            <BaseButton type="secondary">Secondary</BaseButton>
            <BaseButton type="info">Info</BaseButton>
            <BaseButton type="success">Success</BaseButton>
            <BaseButton type="danger">Danger</BaseButton>
            <BaseButton type="warning">Warning</BaseButton>
          </div>
        </Card>
        <!-- Outline -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Outline</h3>
          </div>
          <div class="card-body">
            <BaseButton outline type="default">Default</BaseButton>
            <BaseButton outline type="primary">Primary</BaseButton>
            <BaseButton outline type="secondary">Secondary</BaseButton>
            <BaseButton outline type="info">Info</BaseButton>
            <BaseButton outline type="success">Success</BaseButton>
            <BaseButton outline type="danger">Danger</BaseButton>
            <BaseButton outline type="warning">Warning</BaseButton>
          </div>
        </Card>
        <!-- Sizes -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Sizes</h3>
          </div>
          <div class="card-body">
            <BaseButton size="lg" type="primary">Large button</BaseButton>
            <BaseButton size="lg" type="secondary">Large button</BaseButton>
            <hr />
            <BaseButton size="sm" type="primary">Small button</BaseButton>
            <BaseButton size="sm" type="secondary">Small button</BaseButton>
            <hr />
            <BaseButton block type="primary" className="mb-0">
              Block level button
            </BaseButton>
            <BaseButton block type="secondary">Block level button</BaseButton>
          </div>
        </Card>
        <!-- Group -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Group</h3>
          </div>
          <div class="card-body">
            <div class="btn-group" role="group" aria-label="Basic Example">
              <BaseButton type="secondary">Left</BaseButton>
              <BaseButton type="secondary" className="active">
                Middle
              </BaseButton>
              <BaseButton type="secondary">Right</BaseButton>
            </div>
            <hr />
            <div class="btn-group">
              <BaseButton type="info" className="active">1</BaseButton>
              <BaseButton type="info">2</BaseButton>
              <BaseButton type="info">3</BaseButton>
              <BaseButton type="info">4</BaseButton>
            </div>
            <div class="btn-group">
              <BaseButton type="default">5</BaseButton>
              <BaseButton type="default">6</BaseButton>
              <BaseButton type="default">7</BaseButton>
            </div>
          </div>
        </Card>
        <!-- Social -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Social</h3>
          </div>
          <div class="card-body">
            <BaseButton icon className="btn-facebook btn-icon">
              <span class="btn-inner--icon">
                <i class="fab fa-facebook" />
              </span>
              <span class="btn-inner--text">Facebook</span>
            </BaseButton>
            <BaseButton icon className="btn-twitter">
              <span class="btn-inner--icon">
                <i class="fab fa-twitter" />
              </span>
              <span class="btn-inner--text">Twitter</span>
            </BaseButton>
            <BaseButton icon className="btn-google-plus">
              <span class="btn-inner--icon">
                <i class="fab fa-google-plus-g" />
              </span>
              <span class="btn-inner--text">Google +</span>
            </BaseButton>
            <BaseButton icon className="btn-instagram">
              <span class="btn-inner--icon">
                <i class="fab fa-instagram" />
              </span>
              <span class="btn-inner--text">Instagram</span>
            </BaseButton>
            <BaseButton icon className="btn-pinterest">
              <span class="btn-inner--icon">
                <i class="fab fa-pinterest" />
              </span>
              <span class="btn-inner--text">Pinterest</span>
            </BaseButton>
            <BaseButton icon className="btn-youtube">
              <span class="btn-inner--icon">
                <i class="fab fa-youtube" />
              </span>
              <span class="btn-inner--text">Youtube</span>
            </BaseButton>
            <BaseButton icon className="btn-vimeo">
              <span class="btn-inner--icon">
                <i class="fab fa-vimeo-v" />
              </span>
              <span class="btn-inner--text">Vimeo</span>
            </BaseButton>
            <BaseButton icon className="btn-slack">
              <span class="btn-inner--icon">
                <i class="fab fa-slack" />
              </span>
              <span class="btn-inner--text">Slack</span>
            </BaseButton>
            <BaseButton icon className="btn-dribbbleb">
              <span class="btn-inner--icon">
                <i class="fab fa-dribbble" />
              </span>
              <span class="btn-inner--text">Dribbble</span>
            </BaseButton>
            <hr />
            <BaseButton className="btn-facebook btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-facebook" />
              </span>
            </BaseButton>
            <BaseButton className="btn-twitter btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-twitter" />
              </span>
            </BaseButton>
            <BaseButton className="btn-google-plus btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-google-plus-g" />
              </span>
            </BaseButton>
            <BaseButton className="btn-instagram btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-instagram" />
              </span>
            </BaseButton>
            <BaseButton className="btn-pinterest btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-pinterest" />
              </span>
            </BaseButton>
            <BaseButton className="btn-youtube btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-youtube" />
              </span>
            </BaseButton>
            <BaseButton className="btn-vimeo btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-vimeo-v" />
              </span>
            </BaseButton>
            <BaseButton className="btn-slack btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-slack" />
              </span>
            </BaseButton>
            <BaseButton className="btn-dribbble btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-dribbble" />
              </span>
            </BaseButton>
            <hr />
            <BaseButton round className="btn-facebook btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-facebook" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-twitter btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-twitter" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-google-plus btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-google-plus-g" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-instagram btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-instagram" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-pinterest btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-pinterest" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-youtube btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-youtube" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-vimeo btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-vimeo-v" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-slack btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-slack" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-dribbble btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-dribbble" />
              </span>
            </BaseButton>
          </div>
        </Card>
      </div>
    </div>
  </div>

</div>

// extracted_templates/react/argon-dashboard-pro-material-ui-v1.0.0/src/views/admin/Components/Buttons.js
import React from "react";
import clsx from "clsx";
// @material-ui/core components
import { makeStyles } from "@material-ui/core/styles";
import Box from "@material-ui/core/Box";
import Button from "@material-ui/core/Button";
import ButtonGroup from "@material-ui/core/ButtonGroup";
import Card from "@material-ui/core/Card";
import CardContent from "@material-ui/core/CardContent";
import CardHeader from "@material-ui/core/CardHeader";
import Container from "@material-ui/core/Container";
import Divider from "@material-ui/core/Divider";
import Grid from "@material-ui/core/Grid";
import IconButton from "@material-ui/core/IconButton";
// @material-ui/icons components
import Archive from "@material-ui/icons/Archive";
import Grain from "@material-ui/icons/Grain";
// core components
import SimpleHeader from "components/Headers/SimpleHeader.js";

import componentStyles from "assets/theme/views/admin/buttons.js";
import componentStylesButtons from "assets/theme/components/button.js";

const useStyles = makeStyles(componentStyles);
const useStylesButtons = makeStyles(componentStylesButtons);

const socialButtonColors = [
  {
    icon: "fab fa-facebook",
    text: "Facebook",
    color: "buttonContainedFacebook",
  },
  {
    icon: "fab fa-twitter",
    text: "Twitter",
    color: "buttonContainedTwitter",
  },
  {
    icon: "fab fa-google-plus-g",
    text: "Google +",
    color: "buttonContainedGoogle",
  },
  {
    icon: "fab fa-instagram",
    text: "Instagram",
    color: "buttonContainedInstagram",
  },
  {
    icon: "fab fa-pinterest",
    text: "Pinterest",
    color: "buttonContainedPinterest",
  },
  {
    icon: "fab fa-youtube",
    text: "Youtube",
    color: "buttonContainedYoutube",
  },
  {
    icon: "fab fa-vimeo-v",
    text: "Vimeo",
    color: "buttonContainedVimeo",
  },
  {
    icon: "fab fa-slack",
    text: "Slack",
    color: "buttonContainedSlack",
  },
  {
    icon: "fab fa-dribbble",
    text: "Dribbble",
    color: "buttonContainedDribbble",
  },
  {
    icon: "fab fa-github",
    text: "Github",
    color: "buttonContainedGithub",
  },
];

const Buttons = () => {
  const classes = { ...useStyles(), ...useStylesButtons() };
  return (
    <>
      <SimpleHeader section="Buttons" subsection="Components" />
      {/* Page content */}
      <Container
        maxWidth={false}
        component={Box}
        marginTop="-4.5rem"
        classes={{ root: classes.containerRoot }}
      >
        {/* Table */}
        <Grid
          container
          component={Box}
          marginBottom="39px"
          justifyContent="center"
        >
          <Grid item xs={12} lg={8}>
            <Card classes={{ root: classes.cardRoot }}>
              <CardHeader
                className={classes.cardHeader}
                title="Styles"
                titleTypographyProps={{
                  component: Box,
                  marginBottom: "0!important",
                  variant: "h3",
                }}
              ></CardHeader>
              <CardContent>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="primary" variant="contained">
                    Button
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="primary" variant="contained">
                    <Box
                      component={Archive}
                      marginRight=".75em"
                      top="-2px"
                      position="relative"
                    />
                    With Icons
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="primary" variant="contained">
                    <Box component={Grain} top="-2px" position="relative" />
                  </Button>
                </Box>
              </CardContent>
            </Card>
            <Card classes={{ root: classes.cardRoot }}>
              <CardHeader
                className={classes.cardHeader}
                title="Colors"
                titleTypographyProps={{
                  component: Box,
                  marginBottom: "0!important",
                  variant: "h3",
                }}
              ></CardHeader>
              <CardContent>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button variant="contained">Default</Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="primary" variant="contained">
                    Primary
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="secondary" variant="contained">
                    Secondary
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="contained"
                    classes={{
                      root: classes.buttonContainedInfo,
                    }}
                  >
                    Info
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="contained"
                    classes={{
                      root: classes.buttonContainedSuccess,
                    }}
                  >
                    Success
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="contained"
                    classes={{
                      root: classes.buttonContainedError,
                    }}
                  >
                    Error
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="contained"
                    classes={{
                      root: classes.buttonContainedWarning,
                    }}
                  >
                    Warning
                  </Button>
                </Box>
              </CardContent>
            </Card>
            <Card classes={{ root: classes.cardRoot }}>
              <CardHeader
                className={classes.cardHeader}
                title="Outline"
                titleTypographyProps={{
                  component: Box,
                  marginBottom: "0!important",
                  variant: "h3",
                }}
              ></CardHeader>
              <CardContent>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button variant="outlined">Default</Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="primary" variant="outlined">
                    Primary
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button color="secondary" variant="outlined">
                    Secondary
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="outlined"
                    classes={{
                      root: classes.buttonOutlineInfo,
                    }}
                  >
                    Info
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="outlined"
                    classes={{
                      root: classes.buttonOutlineSuccess,
                    }}
                  >
                    Success
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="outlined"
                    classes={{
                      root: classes.buttonOutlineError,
                    }}
                  >
                    Error
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button
                    variant="outlined"
                    classes={{
                      root: classes.buttonOutlineWarning,
                    }}
                  >
                    Warning
                  </Button>
                </Box>
              </CardContent>
            </Card>
            <Card classes={{ root: classes.cardRoot }}>
              <CardHeader
                className={classes.cardHeader}
                title="Sizes"
                titleTypographyProps={{
                  component: Box,
                  marginBottom: "0!important",
                  variant: "h3",
                }}
              ></CardHeader>
              <CardContent>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button size="large" color="primary" variant="contained">
                    Large button
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button size="large" color="secondary" variant="contained">
                    Large button
                  </Button>
                </Box>
                <Box
                  component={Divider}
                  marginTop="2rem!important"
                  marginBottom="2rem!important"
                />
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button size="small" color="primary" variant="contained">
                    Small button
                  </Button>
                </Box>
                <Box
                  display="inline-block"
                  marginRight="1rem"
                  marginBottom="1rem"
                >
                  <Button size="small" color="secondary" variant="contained">
                    Small button
                  </Button>
                </Box>
                <Box
                  component={Divider}
                  marginTop="2rem!important"
                  marginBottom="2rem!important"
                />
                <Box display="block" marginBottom="1rem">
                  <Button color="primary" variant="contained" fullWidth>
                    Block level
                  </Button>
                </Box>
                <Button color="secondary" variant="contained" fullWidth>
                  Block level
                </Button>
              </CardContent>
            </Card>
            <Card classes={{ root: classes.cardRoot }}>
              <CardHeader
                className={classes.cardHeader}
                title="Group"
                titleTypographyProps={{
                  component: Box,
                  marginBottom: "0!important",
                  variant: "h3",
                }}
              ></CardHeader>
              <CardContent>
                <ButtonGroup
                  variant="contained"
                  color="secondary"
                  aria-label="contained-secondary-button-group"
                >
                  <Button>Left</Button>
                  <Button>Middle</Button>
                  <Button>Right</Button>
                </ButtonGroup>
                <Box
                  component={Divider}
                  marginTop="2rem!important"
                  marginBottom="2rem!important"
                />
                <Box
                  display="inline-block"
                  marginRight=".25rem"
                  marginBottom="1rem"
                >
                  <ButtonGroup
                    variant="contained"
                    aria-label="contained-info-button-group"
                    classes={{
                      groupedContained: clsx(
                        classes.butttonInfoContainedGroup,
                        classes.letterSpacingInherit
                      ),
                    }}
                  >
                    <Button>1</Button>
                    <Button>2</Button>
                    <Button>3</Button>
                    <Button>4</Button>
                  </ButtonGroup>
                </Box>
                <ButtonGroup
                  variant="contained"
                  color="default"
                  aria-label="contained-default-button-group"
                  classes={{
                    groupedContained: classes.letterSpacingInherit,
                  }}
                >
                  <Button>5</Button>
                  <Button>6</Button>
                  <Button>7</Button>
                </ButtonGroup>
              </CardContent>
            </Card>
            <Card classes={{ root: classes.cardRoot }}>
              <CardHeader
                className={classes.cardHeader}
                title="Social"
                titleTypographyProps={{
                  component: Box,
                  marginBottom: "0!important",
                  variant: "h3",
                }}
              ></CardHeader>
              <CardContent>
                {socialButtonColors.map((prop, key) => (
                  <Box
                    key={key}
                    display="inline-block"
                    marginRight="1rem"
                    marginBottom="1rem"
                  >
                    <Button
                      variant="contained"
                      classes={{ root: classes[prop.color] }}
                    >
                      <Box
                        component="i"
                        marginRight=".5rem"
                        className={prop.icon}
                      />
                      {prop.text}
                    </Button>
                  </Box>
                ))}
                <Box
                  component={Divider}
                  marginTop="2rem!important"
                  marginBottom="2rem!important"
                />
                {socialButtonColors.map((prop, key) => (
                  <Box
                    key={key}
                    display="inline-block"
                    marginRight="1rem"
                    marginBottom="1rem"
                  >
                    <Button
                      variant="contained"
                      classes={{
                        root: clsx(classes[prop.color], classes.buttonIconOnly),
                      }}
                    >
                      <Box component="i" className={prop.icon} />
                    </Button>
                  </Box>
                ))}
                <Box
                  component={Divider}
                  marginTop="2rem!important"
                  marginBottom="2rem!important"
                />
                {socialButtonColors.map((prop, key) => (
                  <Box
                    key={key}
                    display="inline-block"
                    marginRight="1rem"
                    marginBottom="1rem"
                  >
                    <IconButton
                      variant="contained"
                      classes={{
                        root: clsx(classes[prop.color], classes.buttonIconOnly),
                      }}
                    >
                      <Box
                        fontSize="14px"
                        component="i"
                        className={prop.icon}
                      />
                    </IconButton>
                  </Box>
                ))}
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      </Container>
    </>
  );
};

export default Buttons;
