// extracted_templates/vue-laravel/creativetimofficial-vue-argon-dashboard-pro-laravel-fd914dc1b5592a1ab5fc7c53e0f906bea8dd3b9e/creativetimofficial-vue-argon-dashboard-pro-laravel-fd914dc1b5592a1ab5fc7c53e0f906bea8dd3b9e/vue-argon-dashboard-laravel-pro/src/App.vue
<!--
=========================================================
* Vue Argon Dashboard 2 PRO - v3.0.0
=========================================================

* Product Page: https://creative-tim.com/product/vue-argon-dashboard-pro
* Copyright 2022 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

<template>
  <div
    v-show="layout === 'landing'"
    class="landing-bg h-100 bg-gradient-primary position-fixed w-100"
  ></div>
  <sidenav v-if="showSidenav" />
  <main class="main-content position-relative max-height-vh-100 h-100">
    <navbar v-if="showNavbar" />
    <router-view />
    <app-footer v-show="showFooter" />
    <configurator
      :class="[showConfig ? 'show' : '', hideConfigButton ? 'd-none' : '']"
    />
  </main>
</template>
<script>
import Sidenav from "./examples/Sidenav";
import Configurator from "@/examples/Configurator.vue";
import Navbar from "@/examples/Navbars/Navbar.vue";
import AppFooter from "@/examples/Footer.vue";
import { mapState } from "vuex";

export default {
  name: "App",
  components: {
    Sidenav,
    Configurator,
    Navbar,
    AppFooter
  },
  computed: {
    ...mapState([
      "layout",
      "showSidenav",
      "showNavbar",
      "showFooter",
      "showConfig",
      "hideConfigButton"
    ])
  }
};
</script>

// extracted_templates/react/muse-ant-design-dashboard-pro-v1.1.0/muse-ant-design-dashboard-pro-v1.1.0/src/App.js
/*!
=========================================================
* Muse Ant Design Dashboard PRO - v1.1.0
=========================================================
* Product Page: https://www.creative-tim.com/product/muse-ant-design-dashboard-pro
* Copyright 2023 Creative Tim (https://www.creative-tim.com)
* Coded by Creative Tim
=========================================================
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*/

import "antd/dist/antd.min.css";
import "antd-button-color/dist/css/style.css";
import "./App.css";
import "./responsive.css";
import { BrowserRouter, Switch, Route, Redirect } from "react-router-dom";

import SignUp from "./component/pages/SignUp";

import Main from "./component/layout/main";
import Pricing from "./component/pages/Pricing";
import Cover from "./component/authentication/signup/Cover";
import Illustration from "./component/authentication/signup/Illustration";
import PageFound from "./component/pages/PageFound";

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <Switch>
          <Route path="/sign-up" exact component={SignUp} />
          <Route
            path="/authentication/sign-up/basic"
            exact
            component={SignUp}
          />
          <Route path="/authentication/sign-up/cover" exact component={Cover} />
          <Route
            path="/authentication/sign-up/illustration"
            exact
            component={Illustration}
          />
          <Route path="/sign-in" exact component={PageFound} />
          {/* <Route path="/sign-in" exact component={SignIn} /> */}
          <Route path="/pages/pricing" exact component={Pricing} />

          <Route path="/:id" component={Main} />

          <Redirect
            to={{
              pathname: "/dashboard",
            }}
          />
        </Switch>
      </BrowserRouter>
    </div>
  );
}

export default App;
