// extracted_templates/react-node/argon-dashboard-pro-react-nodejs-v1.0.0/argon-dashboard-pro-react-nodejs-v1.0.0/frontend/src/views/pages/components/Buttons.js
/*!

=========================================================
* Argon Dashboard PRO React Nodejs - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard-pro-react-nodejs
* Copyright 2021 Creative Tim (http://www.creative-tim.com)

* Coded by Creative Tim
* Coded by ProjectData

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
*/
// reactstrap components
import {
  Button,
  ButtonGroup,
  Card,
  CardHeader,
  CardBody,
  Container,
  Row,
  Col,
} from "reactstrap";
// core components
import SimpleHeader from "components/Headers/SimpleHeader.js";

function Buttons() {
  return (
    <>
      <SimpleHeader name="Buttons" parentName="Components" />
      <Container className="mt--6" fluid>
        <Row className="justify-content-center">
          <Col className="card-wrapper ct-example" lg="8">
            <Card>
              <CardHeader>
                <h3 className="mb-0">Styles</h3>
              </CardHeader>
              <CardBody>
                <Button color="primary" type="button">
                  Button
                </Button>
                <Button className="btn-icon" color="primary" type="button">
                  <span className="btn-inner--icon mr-1">
                    <i className="ni ni-bag-17" />
                  </span>
                  <span className="btn-inner--text">With icon</span>
                </Button>
                <Button className="btn-icon" color="primary" type="button">
                  <span className="btn-inner--icon">
                    <i className="ni ni-atom" />
                  </span>
                </Button>
              </CardBody>
            </Card>

            <Card>
              <CardHeader>
                <h3 className="mb-0">Colors</h3>
              </CardHeader>
              <CardBody>
                <Button color="default" type="button">
                  Default
                </Button>
                <Button color="primary" type="button">
                  Primary
                </Button>
                <Button color="secondary" type="button">
                  Secondary
                </Button>
                <Button color="info" type="button">
                  Info
                </Button>
                <Button color="success" type="button">
                  Success
                </Button>
                <Button color="danger" type="button">
                  Danger
                </Button>
                <Button color="warning" type="button">
                  Warning
                </Button>
              </CardBody>
            </Card>

            <Card>
              <CardHeader>
                <h3 className="mb-0">Outline</h3>
              </CardHeader>
              <CardBody>
                <Button color="default" outline type="button">
                  Default
                </Button>
                <Button color="primary" outline type="button">
                  Primary
                </Button>
                <Button color="secondary" outline type="button">
                  Secondary
                </Button>
                <Button color="info" outline type="button">
                  Info
                </Button>
                <Button color="success" outline type="button">
                  Success
                </Button>
                <Button color="danger" outline type="button">
                  Danger
                </Button>
                <Button color="warning" outline type="button">
                  Warning
                </Button>
              </CardBody>
            </Card>

            <Card>
              <CardHeader>
                <h3 className="mb-0">Sizes</h3>
              </CardHeader>
              <CardBody>
                <Button color="primary" size="lg" type="button">
                  Large button
                </Button>
                <Button color="secondary" size="lg" type="button">
                  Large button
                </Button>
                <hr />
                <Button color="primary" size="sm" type="button">
                  Small button
                </Button>
                <Button color="secondary" size="sm" type="button">
                  Small button
                </Button>
                <hr />
                <Button block color="primary" size="lg" type="button">
                  Block level button
                </Button>
                <Button block color="secondary" size="lg" type="button">
                  Block level button
                </Button>
              </CardBody>
            </Card>

            <Card>
              <CardHeader>
                <h3 className="mb-0">Group</h3>
              </CardHeader>
              <CardBody>
                <ButtonGroup aria-label="Basic example" role="group">
                  <Button color="secondary" type="button">
                    Left
                  </Button>
                  <Button className="active" color="secondary" type="button">
                    Middle
                  </Button>
                  <Button color="secondary" type="button">
                    Right
                  </Button>
                </ButtonGroup>
                <hr />
                <ButtonGroup>
                  <Button className="active" color="info" type="button">
                    1
                  </Button>
                  <Button color="info" type="button">
                    2
                  </Button>
                  <Button color="info" type="button">
                    3
                  </Button>
                  <Button color="info" type="button">
                    4
                  </Button>
                </ButtonGroup>
                <ButtonGroup>
                  <Button color="default" type="button">
                    5
                  </Button>
                  <Button color="default" type="button">
                    6
                  </Button>
                  <Button color="default" type="button">
                    7
                  </Button>
                </ButtonGroup>
              </CardBody>
            </Card>
            <Card>
              <CardHeader>
                <h3 className="mb-0">Social</h3>
              </CardHeader>
              <CardBody>
                <Button
                  className="btn-icon my-2"
                  color="facebook"
                  type="button"
                >
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-facebook" />
                  </span>
                  <span className="btn-inner--text">Facebook</span>
                </Button>
                <Button className="btn-icon" color="twitter" type="button">
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-twitter" />
                  </span>
                  <span className="btn-inner--text">Twitter</span>
                </Button>
                <Button
                  className="btn-google-plus btn-icon"
                  color="google"
                  type="button"
                >
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-google-plus-g" />
                  </span>
                  <span className="btn-inner--text">Google +</span>
                </Button>
                <Button
                  className="btn-instagram btn-icon"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-instagram" />
                  </span>
                  <span className="btn-inner--text">Instagram</span>
                </Button>
                <Button className="btn-icon" color="pinterest" type="button">
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-pinterest" />
                  </span>
                  <span className="btn-inner--text">Pinterest</span>
                </Button>
                <Button className="btn-icon" color="youtube" type="button">
                  <span className="btn-inner--icon">
                    <i className="fab fa-youtube" />
                  </span>
                  <span className="btn-inner--text">Youtube</span>
                </Button>
                <Button
                  className="btn-vimeo btn-icon"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-vimeo-v" />
                  </span>
                  <span className="btn-inner--text">Vimeo</span>
                </Button>
                <Button
                  className="btn-slack btn-icon"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-slack" />
                  </span>
                  <span className="btn-inner--text">Slack</span>
                </Button>
                <Button className="btn-icon" color="dribbble" type="button">
                  <span className="btn-inner--icon mr-1">
                    <i className="fab fa-dribbble" />
                  </span>
                  <span className="btn-inner--text">Dribbble</span>
                </Button>
                <hr />
                <Button
                  className="btn-icon-only"
                  color="facebook"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-facebook" />
                  </span>
                </Button>
                <Button className="btn-icon-only" color="twitter" type="button">
                  <span className="btn-inner--icon">
                    <i className="fab fa-twitter" />
                  </span>
                </Button>
                <Button
                  className="btn-google-plus btn-icon-only"
                  color="google"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-google-plus-g" />
                  </span>
                </Button>
                <Button
                  className="btn-instagram btn-icon-only"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-instagram" />
                  </span>
                </Button>
                <Button
                  className="btn-icon-only"
                  color="pinterest"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-pinterest" />
                  </span>
                </Button>
                <Button className="btn-icon-only" color="youtube" type="button">
                  <span className="btn-inner--icon">
                    <i className="fab fa-youtube" />
                  </span>
                </Button>
                <Button
                  className="btn-vimeo btn-icon-only"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-vimeo-v" />
                  </span>
                </Button>
                <Button
                  className="btn-slack btn-icon-only"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-slack" />
                  </span>
                </Button>
                <Button
                  className="btn-icon-only"
                  color="dribbble"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-dribbble" />
                  </span>
                </Button>
                <hr />
                <Button
                  className="btn-icon-only rounded-circle"
                  color="facebook"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-facebook" />
                  </span>
                </Button>
                <Button
                  className="btn-icon-only rounded-circle"
                  color="twitter"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-twitter" />
                  </span>
                </Button>
                <Button
                  className="btn-google-plus btn-icon-only rounded-circle"
                  color="google"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-google-plus-g" />
                  </span>
                </Button>
                <Button
                  className="btn-instagram btn-icon-only rounded-circle"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-instagram" />
                  </span>
                </Button>
                <Button
                  className="btn-icon-only rounded-circle"
                  color="pinterest"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-pinterest" />
                  </span>
                </Button>
                <Button
                  className="btn-icon-only rounded-circle"
                  color="youtube"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-youtube" />
                  </span>
                </Button>
                <Button
                  className="btn-vimeo btn-icon-only rounded-circle"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-vimeo-v" />
                  </span>
                </Button>
                <Button
                  className="btn-slack btn-icon-only rounded-circle"
                  color="default"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-slack" />
                  </span>
                </Button>
                <Button
                  className="btn-icon-only rounded-circle"
                  color="dribbble"
                  type="button"
                >
                  <span className="btn-inner--icon">
                    <i className="fab fa-dribbble" />
                  </span>
                </Button>
              </CardBody>
            </Card>
          </Col>
        </Row>
      </Container>
    </>
  );
}

export default Buttons;

// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/components/buttons.svelte
<script>
  import BaseHeader from "../../../components/BaseHeader.svelte";
  import RouteBreadcrumb from "../../../components/Breadcrumb/RouteBreadcrumb.svelte";
  import BaseButton from "../../../components/BaseButton.svelte";
  import Card from "../../../components/Cards/Card.svelte";
  export let name = "Buttons";
  import { fade } from "svelte/transition";
  import { onMount } from "svelte";
  onMount(function() {
    let topmenu = document.getElementsByTagName("nav").item(0);
    topmenu.classList.add("bg-danger");
    topmenu.classList.add("navbar-dark");
    topmenu.classList.remove("navbar-light");
    let search = document.getElementsByTagName("form").item(0);
    search.classList.remove("navbar-search-dark");
    search.classList.add("navbar-search-light");
  });
</script>

<div transition:fade={{ duration: 250 }}>
  <BaseHeader className="pb-6">
    <div class="row align-items-center py-4">
      <div class="col-lg-6 col-7">
        <h6 class="h2 text-white d-inline-block mb-0">{name}</h6>
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
          <RouteBreadcrumb {name} />
        </nav>
      </div>
      <div class="col-lg-6 col-5 text-right">
        <BaseButton size="sm" type="neutral">New</BaseButton>
        <BaseButton size="sm" type="neutral">Filters</BaseButton>
      </div>
    </div>
  </BaseHeader>

  <div class="container-fluid mt--6">
    <div class="row justify-content-center">
      <div class="col-lg-8 card-wrapper ct-example">
        <!-- Styles -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Styles</h3>
          </div>
          <div class="card-body">
            <BaseButton icon type="primary">Button</BaseButton>
            <BaseButton icon type="primary">
              <span class="btn-inner--icon">
                <i class="ni ni-bag-17" />
              </span>
              <span class="btn-inner--text">With icon</span>
            </BaseButton>
            <BaseButton icon type="primary">
              <span class="btn-inner--icon">
                <i class="ni ni-atom" />
              </span>
            </BaseButton>
          </div>
        </Card>
        <!-- Colors -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Colors</h3>
          </div>
          <div class="card-body">
            <BaseButton type="default">Default</BaseButton>
            <BaseButton type="primary">Primary</BaseButton>
            <BaseButton type="secondary">Secondary</BaseButton>
            <BaseButton type="info">Info</BaseButton>
            <BaseButton type="success">Success</BaseButton>
            <BaseButton type="danger">Danger</BaseButton>
            <BaseButton type="warning">Warning</BaseButton>
          </div>
        </Card>
        <!-- Outline -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Outline</h3>
          </div>
          <div class="card-body">
            <BaseButton outline type="default">Default</BaseButton>
            <BaseButton outline type="primary">Primary</BaseButton>
            <BaseButton outline type="secondary">Secondary</BaseButton>
            <BaseButton outline type="info">Info</BaseButton>
            <BaseButton outline type="success">Success</BaseButton>
            <BaseButton outline type="danger">Danger</BaseButton>
            <BaseButton outline type="warning">Warning</BaseButton>
          </div>
        </Card>
        <!-- Sizes -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Sizes</h3>
          </div>
          <div class="card-body">
            <BaseButton size="lg" type="primary">Large button</BaseButton>
            <BaseButton size="lg" type="secondary">Large button</BaseButton>
            <hr />
            <BaseButton size="sm" type="primary">Small button</BaseButton>
            <BaseButton size="sm" type="secondary">Small button</BaseButton>
            <hr />
            <BaseButton block type="primary" className="mb-0">
              Block level button
            </BaseButton>
            <BaseButton block type="secondary">Block level button</BaseButton>
          </div>
        </Card>
        <!-- Group -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Group</h3>
          </div>
          <div class="card-body">
            <div class="btn-group" role="group" aria-label="Basic Example">
              <BaseButton type="secondary">Left</BaseButton>
              <BaseButton type="secondary" className="active">
                Middle
              </BaseButton>
              <BaseButton type="secondary">Right</BaseButton>
            </div>
            <hr />
            <div class="btn-group">
              <BaseButton type="info" className="active">1</BaseButton>
              <BaseButton type="info">2</BaseButton>
              <BaseButton type="info">3</BaseButton>
              <BaseButton type="info">4</BaseButton>
            </div>
            <div class="btn-group">
              <BaseButton type="default">5</BaseButton>
              <BaseButton type="default">6</BaseButton>
              <BaseButton type="default">7</BaseButton>
            </div>
          </div>
        </Card>
        <!-- Social -->
        <Card noBody className="card">
          <div slot="header">
            <h3 class="mb-0">Social</h3>
          </div>
          <div class="card-body">
            <BaseButton icon className="btn-facebook btn-icon">
              <span class="btn-inner--icon">
                <i class="fab fa-facebook" />
              </span>
              <span class="btn-inner--text">Facebook</span>
            </BaseButton>
            <BaseButton icon className="btn-twitter">
              <span class="btn-inner--icon">
                <i class="fab fa-twitter" />
              </span>
              <span class="btn-inner--text">Twitter</span>
            </BaseButton>
            <BaseButton icon className="btn-google-plus">
              <span class="btn-inner--icon">
                <i class="fab fa-google-plus-g" />
              </span>
              <span class="btn-inner--text">Google +</span>
            </BaseButton>
            <BaseButton icon className="btn-instagram">
              <span class="btn-inner--icon">
                <i class="fab fa-instagram" />
              </span>
              <span class="btn-inner--text">Instagram</span>
            </BaseButton>
            <BaseButton icon className="btn-pinterest">
              <span class="btn-inner--icon">
                <i class="fab fa-pinterest" />
              </span>
              <span class="btn-inner--text">Pinterest</span>
            </BaseButton>
            <BaseButton icon className="btn-youtube">
              <span class="btn-inner--icon">
                <i class="fab fa-youtube" />
              </span>
              <span class="btn-inner--text">Youtube</span>
            </BaseButton>
            <BaseButton icon className="btn-vimeo">
              <span class="btn-inner--icon">
                <i class="fab fa-vimeo-v" />
              </span>
              <span class="btn-inner--text">Vimeo</span>
            </BaseButton>
            <BaseButton icon className="btn-slack">
              <span class="btn-inner--icon">
                <i class="fab fa-slack" />
              </span>
              <span class="btn-inner--text">Slack</span>
            </BaseButton>
            <BaseButton icon className="btn-dribbbleb">
              <span class="btn-inner--icon">
                <i class="fab fa-dribbble" />
              </span>
              <span class="btn-inner--text">Dribbble</span>
            </BaseButton>
            <hr />
            <BaseButton className="btn-facebook btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-facebook" />
              </span>
            </BaseButton>
            <BaseButton className="btn-twitter btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-twitter" />
              </span>
            </BaseButton>
            <BaseButton className="btn-google-plus btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-google-plus-g" />
              </span>
            </BaseButton>
            <BaseButton className="btn-instagram btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-instagram" />
              </span>
            </BaseButton>
            <BaseButton className="btn-pinterest btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-pinterest" />
              </span>
            </BaseButton>
            <BaseButton className="btn-youtube btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-youtube" />
              </span>
            </BaseButton>
            <BaseButton className="btn-vimeo btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-vimeo-v" />
              </span>
            </BaseButton>
            <BaseButton className="btn-slack btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-slack" />
              </span>
            </BaseButton>
            <BaseButton className="btn-dribbble btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-dribbble" />
              </span>
            </BaseButton>
            <hr />
            <BaseButton round className="btn-facebook btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-facebook" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-twitter btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-twitter" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-google-plus btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-google-plus-g" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-instagram btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-instagram" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-pinterest btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-pinterest" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-youtube btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-youtube" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-vimeo btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-vimeo-v" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-slack btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-slack" />
              </span>
            </BaseButton>
            <BaseButton round className="btn-dribbble btn-icon-only">
              <span class="btn-inner--icon">
                <i class="fab fa-dribbble" />
              </span>
            </BaseButton>
          </div>
        </Card>
      </div>
    </div>
  </div>

</div>
