// extracted_templates/react/now-ui-dashboard-pro-react-v1.5.2/now-ui-dashboard-pro-react-v1.5.2/src/views/Components/Typography.js
/*!

=========================================================
* Now UI Dashboard PRO React - v1.5.2
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard-pro-react
* Copyright 2023 Creative Tim (https://www.creative-tim.com)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

*/
import React from "react";

// reactstrap components
import { Card, CardHeader, CardBody, Row, Col } from "reactstrap";

// core components
import PanelHeader from "components/PanelHeader/PanelHeader.js";

function Typography() {
  return (
    <>
      <PanelHeader size="sm" />
      <div className="content">
        <Row>
          <Col md={12}>
            <Card>
              <CardHeader>
                <h5 className="title">Now Ui Table Heading</h5>
                <p className="category">Created using Montserrat Font Family</p>
              </CardHeader>
              <CardBody>
                <div className="typography-line">
                  <h1>
                    <span>Header 1</span>The Life of Now Ui Dashboard{" "}
                  </h1>
                </div>
                <div className="typography-line">
                  <h2>
                    <span>Header 2</span>The Life of Now Ui Dashboard{" "}
                  </h2>
                </div>
                <div className="typography-line">
                  <h3>
                    <span>Header 3</span>The Life of Now Ui Dashboard{" "}
                  </h3>
                </div>
                <div className="typography-line">
                  <h4>
                    <span>Header 4</span>The Life of Now Ui Dashboard{" "}
                  </h4>
                </div>
                <div className="typography-line">
                  <h5>
                    <span>Header 5</span>The Life of Now Ui Dashboard{" "}
                  </h5>
                </div>
                <div className="typography-line">
                  <h6>
                    <span>Header 6</span>The Life of Now Ui Dashboard{" "}
                  </h6>
                </div>
                <div className="typography-line">
                  <p>
                    <span>Paragraph</span>I will be the leader of a company that
                    ends up being worth billions of dollars, because I got the
                    answers. I understand culture. I am the nucleus. I think
                    that’s a responsibility that I have, to push possibilities,
                    to show people, this is the level that things could be at.
                  </p>
                </div>
                <div className="typography-line">
                  <span>Quote</span>
                  <blockquote>
                    <p className="blockquote blockquote-primary">
                      "I will be the leader of a company that ends up being
                      worth billions of dollars, because I got the answers. I
                      understand culture. I am the nucleus. I think that’s a
                      responsibility that I have, to push possibilities, to show
                      people, this is the level that things could be at."
                      <br />
                      <br />
                      <small>- Noaa</small>
                    </p>
                  </blockquote>
                </div>

                <div className="typography-line">
                  <span>Muted Text</span>
                  <p className="text-muted">
                    I will be the leader of a company that ends up being worth
                    billions of dollars, because I got the answers...
                  </p>
                </div>
                <div className="typography-line">
                  <span>Primary Text</span>
                  <p className="text-primary">
                    I will be the leader of a company that ends up being worth
                    billions of dollars, because I got the answers...
                  </p>
                </div>
                <div className="typography-line">
                  <span>Info Text</span>
                  <p className="text-info">
                    I will be the leader of a company that ends up being worth
                    billions of dollars, because I got the answers...{" "}
                  </p>
                </div>
                <div className="typography-line">
                  <span>Success Text</span>
                  <p className="text-success">
                    I will be the leader of a company that ends up being worth
                    billions of dollars, because I got the answers...{" "}
                  </p>
                </div>
                <div className="typography-line">
                  <span>Warning Text</span>
                  <p className="text-warning">
                    I will be the leader of a company that ends up being worth
                    billions of dollars, because I got the answers...
                  </p>
                </div>
                <div className="typography-line">
                  <span>Danger Text</span>
                  <p className="text-danger">
                    I will be the leader of a company that ends up being worth
                    billions of dollars, because I got the answers...{" "}
                  </p>
                </div>
                <div className="typography-line">
                  <h2>
                    <span>Small Tag</span>
                    Header with small subtitle <br />
                    <small>Use "small" tag for the headers</small>
                  </h2>
                </div>
              </CardBody>
            </Card>
          </Col>
        </Row>
      </div>
    </>
  );
}

export default Typography;

// extracted_templates/svelte/argon-dashboard-pro-svelte-v1.2.0/argon-dashboard-pro-svelte-v1.2.0/src/views/Dashboard/components/typography.svelte
<script>
  import BaseHeader from "../../../components/BaseHeader.svelte";
  import RouteBreadcrumb from "../../../components/Breadcrumb/RouteBreadcrumb.svelte";
  import BaseButton from "../../../components/BaseButton.svelte";
  import Card from "../../../components/Cards/Card.svelte";
  import { fade } from "svelte/transition";
  export let name = "Typography";
  import { onMount } from "svelte";
  onMount(function() {
    let topmenu = document.getElementsByTagName("nav").item(0);
    topmenu.classList.add("bg-danger");
    topmenu.classList.add("navbar-dark");
    topmenu.classList.remove("navbar-light");
    let search = document.getElementsByTagName("form").item(0);
    search.classList.remove("navbar-search-dark");
    search.classList.add("navbar-search-light");
  });
</script>

<div style="transform-origin: center top;" transition:fade={{ duration: 250 }}>
  <BaseHeader className="pb-6">
    <div class="row align-items-center py-4">
      <div class="col-lg-6 col-7">
        <h6 class="h2 text-white d-inline-block mb-0">{name}</h6>
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
          <RouteBreadcrumb {name} />
        </nav>
      </div>
      <div class="col-lg-6 col-5 text-right">
        <BaseButton size="sm" type="neutral">New</BaseButton>
        <BaseButton size="sm" type="neutral">Filters</BaseButton>
      </div>
    </div>
  </BaseHeader>

  <div class="container-fluid mt--6">
    <div class="row justify-content-center">
      <div class="col-lg-8 card-wrapper">
        <!-- Headings -->
        <Card>
          <h3 slot="header" class="mb-0">Headings</h3>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading 1
              </small>
            </div>
            <div class="col-sm-9">
              <h1 class="mb-0">Argon Dashboard PRO</h1>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading 2
              </small>
            </div>
            <div class="col-sm-9">
              <h2 class="mb-0">Argon Dashboard PRO</h2>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading 3
              </small>
            </div>
            <div class="col-sm-9">
              <h3 class="mb-0">Argon Dashboard PRO</h3>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading 4
              </small>
            </div>
            <div class="col-sm-9">
              <h4 class="mb-0">Argon Dashboard PRO</h4>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading 5
              </small>
            </div>
            <div class="col-sm-9">
              <h5 class="mb-0">Argon Dashboard PRO</h5>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading 6
              </small>
            </div>
            <div class="col-sm-9">
              <h6 class="mb-0">Argon Dashboard PRO</h6>
            </div>
          </div>
        </Card>
        <!-- Display titles -->
        <Card>
          <h3 slot="header" class="mb-0">Display titles</h3>

          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Display 1
              </small>
            </div>
            <div class="col-sm-9">
              <h1 class="display-1 mb-0">Argon Dashboard PRO</h1>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Display 2
              </small>
            </div>
            <div class="col-sm-9">
              <h1 class="display-2 mb-0">Argon Dashboard PRO</h1>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Display 3
              </small>
            </div>
            <div class="col-sm-9">
              <h1 class="display-3 mb-0">Argon Dashboard PRO</h1>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Display 4
              </small>
            </div>
            <div class="col-sm-9">
              <h1 class="display-4 mb-0">Argon Dashboard PRO</h1>
            </div>
          </div>
        </Card>
        <!-- Specialized titles -->
        <Card>
          <h3 slot="header" class="mb-0">Specialized titles</h3>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading
              </small>
            </div>
            <div class="col-sm-9">
              <h3 class="heading mb-0">Argon Dashboard PRO</h3>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading title
              </small>
            </div>
            <div class="col-sm-9">
              <h3 class="heading-title text-warning mb-0">
                Argon Dashboard PRO
              </h3>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Heading title
              </small>
            </div>
            <div class="col-sm-9">
              <div>
                <h2 class="display-3">Header with small subtitle</h2>
                <p class="lead text-muted">
                  According to the National Oceanic and Atmospheric
                  Administration, Ted, Scambos, NSIDClead scentist, puts the
                  potentially record maximum.
                </p>
              </div>
            </div>
          </div>
        </Card>
        <!-- Paragraphs -->
        <Card>
          <h3 slot="header" class="mb-0">Paragraphs</h3>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Paragraph
              </small>
            </div>
            <div class="col-sm-9">
              <p>
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers. I understand
                culture. I am the nucleus. I think that’s a responsibility that
                I have, to push possibilities, to show people, this is the level
                that things could be at.
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Lead text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="lead">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers. I understand
                culture. I am the nucleus. I think that’s a responsibility that
                I have, to push possibilities, to show people, this is the level
                that things could be at.
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Quote
              </small>
            </div>
            <div class="col-sm-9">
              <blockquote class="blockquote">
                <p class="mb-0">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Integer posuere erat a ante.
                </p>
                <footer class="blockquote-footer">
                  Someone famous in
                  <cite title="Source Title">Source Title</cite>
                </footer>
              </blockquote>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Muted text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="text-muted mb-0">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers...
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Primary text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="text-primary">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers...
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Info text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="text-info mb-0">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers...
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Success text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="text-success mb-0">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers...
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Warning text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="text-warning mb-0">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers...
              </p>
            </div>
          </div>
          <div class="row align-items-center py-3">
            <div class="col-sm-3">
              <small class="text-uppercase text-muted font-weight-bold">
                Danger text
              </small>
            </div>
            <div class="col-sm-9">
              <p class="text-danger mb-0">
                I will be the leader of a company that ends up being worth
                billions of dollars, because I got the answers...
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  </div>
</div>
